<?php
/**
 * Equity Framework
 *
 * WARNING: This file is part of the core Equity Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Equity\Templates
 * @author  IDX, LLC
 * @license GPL-2.0+
 * @link    
 */

//* Remove default loop
remove_action( 'equity_loop', 'equity_do_loop' );

add_action( 'equity_loop', 'equity_404' );
/**
 * This function outputs a 404 "Not Found" error message
 *
 * @since 1.0
 */
function equity_404() {

	echo '<article class="entry">';

		printf( '<h1 class="entry-title">%s</h1>', __( 'Page not found, error 404', 'equity' ) );
		echo '<div class="entry-content">';

		echo '<p>' . sprintf( __( 'This content no longer exists. Visit the site\'s <a href="%s">homepage</a> or try a search using the form below.', 'equity' ), home_url() ) . '</p>';

		echo '<p>' . get_search_form() . '</p>';

		echo '</div></article>';

}

equity();
