<?php
/**
 * Equity Framework
 *
 * WARNING: This file is part of the core Equity Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Equity\Templates
 * @author  IDX, LLC
 * @license GPL-2.0+
 * @link    
 */

if ( ! empty( $_SERVER['SCRIPT_FILENAME'] ) && 'comments.php' === basename( $_SERVER['SCRIPT_FILENAME'] ) )
	die ( 'This should not be loaded directly.' );

if ( post_password_required() ) {
	printf( '<p class="alert">%s</p>', __( 'This post is password protected. Please enter the password to view comments.', 'equity' ) );
	return;
}

do_action( 'equity_before_comments' );
do_action( 'equity_comments' );
do_action( 'equity_after_comments' );

do_action( 'equity_before_pings' );
do_action( 'equity_pings' );
do_action( 'equity_after_pings' );

do_action( 'equity_before_comment_form' );
do_action( 'equity_comment_form' );
do_action( 'equity_after_comment_form' );
