<?php
/**
 * Equity Framework
 *
 * WARNING: This file is part of the core Equity Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Equity\Templates
 * @author  IDX, LLC
 * @license GPL-2.0+
 * @link    
 */

equity_structural_wrap( 'site-inner', 'close' );
echo '</div>'; //* end .site-inner

do_action( 'equity_before_footer' );
do_action( 'equity_footer' );
do_action( 'equity_after_footer' );

echo '</div>'; //* end .site-container

do_action( 'equity_after' );
wp_footer(); //* Needed for plugins
?>
</body>
</html>
