<?php
/**
 * Equity Framework
 *
 * WARNING: This file is part of the core Equity Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Equity\Templates
 * @author  IDX, LLC
 * @license GPL-2.0+
 * @link   
 */
?>

<?php do_action( 'equity_doctype' ); ?>
<?php do_action( 'equity_title' ); ?>
<?php do_action( 'equity_meta' ); ?>
<?php wp_head(); //* Needed for plugins ?>
</head>

<?php 
equity_markup( array(
	'html5'   => '<body %s>',
	'context' => 'body',
) );
do_action( 'equity_before' );

equity_markup( array(
	'html5'   => '<div %s>',
	'context' => 'site-container',
) );

do_action( 'equity_before_header' );
do_action( 'equity_header' );
do_action( 'equity_after_header' );

equity_markup( array(
	'html5'   => '<div %s>',
	'context' => 'site-inner',
) );
equity_structural_wrap( 'site-inner' );