<?php
/**
 * Equity Framework
 *
 * WARNING: This file is part of the core Equity Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Equity\Templates
 * @author  IDX, LLC
 * @license GPL-2.0+
 * @link    
 */

//* Output primary sidebar structure
equity_markup( array(
	'html5'   => '<aside %s>',
	'context' => 'sidebar-primary',
) );
do_action( 'equity_before_sidebar_widget_area' );
do_action( 'equity_sidebar' );
do_action( 'equity_after_sidebar_widget_area' );

equity_markup( array(
	'html5' => '</aside>', //* end .sidebar-primary
) );
