<?php
/**
 * Equity Framework
 *
 * WARNING: This file is part of the core Equity Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Equity\Comments
 * @author  IDX, LLC
 * @license GPL-2.0+
 * @link    
 */

add_action( 'equity_after_entry', 'equity_get_comments_template' );
/**
 * Output the comments at the end of entries.
 *
 * Load comments only if we are on a post, page, or CPT that supports comments, and only if comments or trackbacks are enabled.
 *
 * @since 1.0
 *
 * @uses equity_get_option() Get theme setting value.
 *
 * @return null Return early if post type does not support comments.
 */
function equity_get_comments_template() {

	if ( ! post_type_supports( get_post_type(), 'comments' ) )
		return;

	if ( is_singular() && ! in_array( get_post_type(), array( 'post', 'page' ) ) ) {
		comments_template( '', true );
	} elseif ( is_singular( 'post' ) && ( equity_get_option( 'trackbacks_posts' ) || equity_get_option( 'comments_posts' ) ) ) {
		comments_template( '', true );
	} elseif ( is_singular( 'page' ) && ( equity_get_option( 'trackbacks_pages' ) || equity_get_option( 'comments_pages' ) ) ) {
		comments_template( '', true );
	}
}

add_action( 'equity_comments', 'equity_do_comments' );
/**
 * Echo Equity default comment structure.
 *
 * Does the `equity_list_comments` action.
 *
 * Applies the `equity_title_comments`, `equity_prev_comments_link_text`, `equity_next_comments_link_text`, and
 * `equity_comments_closed_text` filters.
 *
 * @since 1.0
 *
 * @uses equity_get_option() Get theme setting value.
 *
 * @global WP_Query $wp_query Query object.
 *
 * @return null Return early if on a page with Equity pages comments off, or on a post with Equity posts comments off.
 */
function equity_do_comments() {

	global $wp_query;

	//* Bail if comments are off for this post type
	if ( ( is_page() && ! equity_get_option( 'comments_pages' ) ) || ( is_single() && ! equity_get_option( 'comments_posts' ) ) )
		return;

	if ( have_comments() && ! empty( $wp_query->comments_by_type['comment'] ) ) {

		equity_markup( array(
			'html5'   => '<div %s>',
			'context' => 'entry-comments',
		) );

		echo apply_filters( 'equity_title_comments', __( '<h3>Comments</h3>', 'equity' ) );
		printf( '<ol %s>', equity_attr( 'comment-list' ) );
			do_action( 'equity_list_comments' );
		echo '</ol>';

		//* Comment Navigation
		$prev_link = get_previous_comments_link( apply_filters( 'equity_prev_comments_link_text', '' ) );
		$next_link = get_next_comments_link( apply_filters( 'equity_next_comments_link_text', '' ) );

		if ( $prev_link || $next_link ) {

			equity_markup( array(
				'html5'   => '<div %s>',
				'context' => 'comments-pagination',
			) );
			
			printf( '<div class="pagination-previous alignleft">%s</div>', $prev_link );
			printf( '<div class="pagination-next alignright">%s</div>', $next_link );
			
			echo '</div>';

		}

		echo '</div>';

	}
	//* No comments so far
	elseif ( 'open' === get_post()->comment_status && $no_comments_text = apply_filters( 'equity_no_comments_text', '' ) ) {
		echo sprintf( '<div %s>', equity_attr( 'entry-comments' ) ) . $no_comments_text . '</div>';
	}
	elseif ( $comments_closed_text = apply_filters( 'equity_comments_closed_text', '' ) ) {
		echo sprintf( '<div %s>', equity_attr( 'entry-comments' ) ) . $comments_closed_text . '</div>';

	}

}

add_action( 'equity_pings', 'equity_do_pings' );
/**
 * Echo Equity default trackback structure.
 *
 * Does the `equity_list_args` action.
 *
 * Applies the `equity_no_pings_text` filter.
 *
 * @since 1.0
 *
 * @uses equity_get_option() Get theme setting value.
 *
 * @global WP_Query $wp_query Query object.
 *
 * @return null Return early if on a page with Equity pages trackbacks off, or on a post with Equity posts trackbacks off.
 */
function equity_do_pings() {

	global $wp_query;

	//* Bail if trackbacks are off for this post type
	if ( ( is_page() && ! equity_get_option( 'trackbacks_pages' ) ) || ( is_single() && ! equity_get_option( 'trackbacks_posts' ) ) )
		return;

	//* If have pings
	if ( have_comments() && !empty( $wp_query->comments_by_type['pings'] ) ) {

		equity_markup( array(
			'html5'   => '<div %s>',
			'context' => 'entry-pings',
		) );

		echo apply_filters( 'equity_title_pings', __( '<h3>Trackbacks</h3>', 'equity' ) );
		echo '<ol class="ping-list">';
			do_action( 'equity_list_pings' );
		echo '</ol>';

		echo '</div>';

	} else {

		echo apply_filters( 'equity_no_pings_text', '' );

	}

}

add_action( 'equity_list_comments', 'equity_default_list_comments' );
/**
 * Output the list of comments.
 *
 * Applies the `equity_comment_list_args` filter.
 *
 * @since 1.0
 *
 * @see equity_comment_callback() HTML5 callback.
 */
function equity_default_list_comments() {

	$defaults = array(
		'type'        => 'comment',
		'avatar_size' => 48,
		'format'      => 'html5', //* Not necessary, but a good example
		'callback'    => 'equity_comment_callback',
	);

	$args = apply_filters( 'equity_comment_list_args', $defaults );

	wp_list_comments( $args );

}

add_action( 'equity_list_pings', 'equity_default_list_pings' );
/**
 * Output the list of trackbacks.
 *
 * Applies the `equity_ping_list_args` filter.
 *
 * @since 1.0
 */
function equity_default_list_pings() {

	$args = apply_filters( 'equity_ping_list_args', array(
		'type' => 'pings',
	) );

	wp_list_comments( $args );

}

/**
 * Comment callback for {@link equity_default_list_comments()} .
 *
 * Does `equity_before_comment` and `equity_after_comment` actions.
 *
 * Applies `comment_author_says_text` and `equity_comment_awaiting_moderation` filters.
 *
 * @since 1.0
 *
 * @param stdClass $comment Comment object.
 * @param array    $args    Comment args.
 * @param integer  $depth   Depth of current comment.
 */
function equity_comment_callback( $comment, array $args, $depth ) {

	$GLOBALS['comment'] = $comment; ?>

	<li <?php comment_class(); ?> id="comment-<?php comment_ID(); ?>">
	<article <?php echo equity_attr( 'comment' ); ?>>

		<?php do_action( 'equity_before_comment' ); ?>

		<header <?php echo equity_attr( 'comment-header' ); ?>>
			<p <?php echo equity_attr( 'comment-author' ); ?>>
				<?php
				echo get_avatar( $comment, $args['avatar_size'] );

				$author = get_comment_author();
				$url    = get_comment_author_url();

				if ( ! empty( $url ) && 'http://' !== $url ) {
					$author = sprintf( '<a href="%s" %s>%s</a>', esc_url( $url ), equity_attr( 'comment-author-link' ), $author );
				}

				/**
				 * Filter the "comment author says" text.
				 *
				 * Allows developer to filter the "comment author says" text so it can say something different, or nothing at all.
				 *
				 * @since 1.0
				 * 
				 * @param string $text Comment author says text.
				 */
				$comment_author_says_text = apply_filters( 'comment_author_says_text', __( 'says', 'equity' ) );

				printf( '<span itemprop="name">%s</span> <span class="says">%s</span>', $author, $comment_author_says_text );
				?>
		 	</p>

			<p <?php echo equity_attr( 'comment-meta' ); ?>>
				<?php				
				printf( '<time %s>', equity_attr( 'comment-time' ) );
				printf( '<a href="%s" %s>', esc_url( get_comment_link( $comment->comment_ID ) ), equity_attr( 'comment-time-link' ) );
				echo    esc_html( get_comment_date() ) . ' ' . __( 'at', 'equity' ) . ' ' . esc_html( get_comment_time() );
				echo    '</a></time>';

				edit_comment_link( __( '(Edit)', 'equity' ), ' ' );
				?>
			</p>
		</header>

		<div <?php echo equity_attr( 'comment-content' ); ?>>
			<?php if ( ! $comment->comment_approved ) : ?>
				<?php
				/**
				 * Filter the "comment awaiting moderation" text.
				 *
				 * Allows developer to filter the "comment awaiting moderation" text so it can say something different, or nothing at all.
				 *
				 * @since 1.0
				 * 
				 * @param string $text Comment awaiting moderation text.
				 */
				$comment_awaiting_moderation_text = apply_filters( 'equity_comment_awaiting_moderation', __( 'Your comment is awaiting moderation.', 'equity' ) );
				?>
				<p class="alert"><?php echo $comment_awaiting_moderation_text; ?></p>
			<?php endif; ?>

			<?php comment_text(); ?>
		</div>

		<?php
		comment_reply_link( array_merge( $args, array(
			'depth'  => $depth,
			'before' => sprintf( '<div %s>', equity_attr( 'comment-reply' ) ),
			'after'  => '</div>',
		) ) );
		?>

		<?php do_action( 'equity_after_comment' ); ?>

	</article>
	<?php
	//* No ending </li> tag because of comment threading

}

add_action( 'equity_comment_form', 'equity_do_comment_form' );
/**
 * Optionally show the comment form.
 *
 * Equity asks WP for the HTML5 version of the comment form.
 *
 * @since 1.0
 *
 * @return null Return early if comments are closed via Equity for this page or post.
 */
function equity_do_comment_form() {

	//* Bail if comments are closed for this post type
	if ( ( is_page() && ! equity_get_option( 'comments_pages' ) ) || ( is_single() && ! equity_get_option( 'comments_posts' ) ) )
		return;

	comment_form( array( 'format' => 'html5' ) );

}

add_filter( 'get_comments_link', 'equity_comments_link_filter', 10, 2 );
/**
 * Filter the comments link. If post has comments, link to #comments div. If no, link to #respond div.
 * 
 * @since 1.0
 */
function equity_comments_link_filter( $link, $post_id ) {

	if ( 0 == get_comments_number() )
		return get_permalink( $post_id ) . '#respond';

	return $link;

}
