<?php
/**
 * Equity Framework
 *
 * WARNING: This file is part of the core Equity Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Equity\Footer
 * @author  IDX, LLC
 * @license GPL-2.0+
 * @link    
 */

add_action( 'equity_before_footer', 'equity_footer_widget_areas' );
/**
 * Echo the markup necessary to facilitate the footer widget areas.
 *
 * The child theme must style the widget areas.
 *
 * Applies the `equity_footer_widget_areas` filter.
 *
 * @since 1.0
 *
 * @uses equity_structural_wrap() Optionally adds wrap with footer-widgets context.
 *
 * @return null Return early if number of widget areas is set to zero, or nothing is added to the first widget area.
 */
function equity_footer_widget_areas() {
	
	$footer_widgets = get_theme_mod( 'footer_widgets' );

	//* Check to see if first widget area has widgets or footer widgets is set to zero. If not, do nothing. No need to check all footer widget areas.
	if ( ! is_active_sidebar( 'footer-1' ) || $footer_widgets == 0)
		return;

	$inside  = '';
	$output  = '';
 	$counter = 1;

 	$span_class = '';

	// span class
	switch ($footer_widgets) {
		case 0:
		case 1:
			$span_class = 'columns small-12 large-12';
			break;
		case 2:
			$span_class = 'columns small-12 medium-6 large-6';
			break;
		case 3:
			$span_class = 'columns small-12 medium-4 large-4';
			break;
		case 4:
			$span_class = 'columns small-12 medium-3 large-3';
			break;
		case 5:
			$span_class = 'columns small-12 medium-3 large-3'; //* not ideal in 12 column grid, use specific css
			break;
		case 6:
			$span_class = 'columns small-12 medium-4 large-2';
			break;
	}

	while ( $counter <= $footer_widgets ) {

		$span_class = apply_filters( 'equity_footer_widgets_class', $span_class, $counter, $footer_widgets );

		//* Darn you, WordPress! Gotta output buffer.
		ob_start();
		dynamic_sidebar( 'footer-' . $counter );
		$widgets = ob_get_clean();

		$inside .= sprintf( '<div class="footer-widgets-%d widget-area %s">%s</div>', $counter, $span_class, $widgets );

		$counter++;

	}

	if ( $inside ) {

		$output .= equity_markup( array(
			'html5'   => '<div %s>',
			'context' => 'footer-widgets',
		) );
	
		$output .= equity_structural_wrap( 'footer-widgets', 'open', 0 );
		
		$output .= $inside;
		
		$output .= equity_structural_wrap( 'footer-widgets', 'close', 0 );
		
		$output .= '</div>';

	}

	echo apply_filters( 'equity_footer_widget_areas', $output, $footer_widgets );

}

add_action( 'equity_footer', 'equity_footer_markup_open', 5 );
/**
 * Echo the opening div tag for the footer.
 *
 * Also optionally adds wrapping div opening tag.
 *
 * @since 1.0
 *
 * @uses equity_structural_wrap() Maybe add opening .wrap div tag with footer context.
 * @uses equity_markup()          Apply contextual markup.
 */
function equity_footer_markup_open() {

	equity_markup( array(
		'html5'   => '<footer %s>',
		'context' => 'site-footer',
	) );
	equity_structural_wrap( 'footer', 'open' );

}

add_action( 'equity_footer', 'equity_footer_markup_close', 15 );
/**
 * Echo the closing div tag for the footer.
 *
 * Also optionally adds wrapping div closing tag.
 *
 * @since 1.0
 *
 * @uses equity_structural_wrap() Maybe add closing .wrap div tag with footer context.
 * @uses equity_markup()          Apply contextual markup.
 */
function equity_footer_markup_close() {

	equity_structural_wrap( 'footer', 'close' );
	equity_markup( array(
		'html5'   => '</footer>',
	) );

}

add_filter( 'equity_footer_output', 'do_shortcode', 20 );
add_filter( 'equity_footer_output', 'wpautop', 20 );
add_action( 'equity_footer', 'equity_do_footer' );
/**
 * Echo the contents of the footer.
 *
 * Execute any shortcodes that might be present.
 *
 * Applies `equity_footer_$option_text` and `equity_footer_output` filters.
 *
 * @since 1.0
 *
 */
function equity_do_footer() {

	global $footer_left, $footer_right, $footer_disclaimer;

	//* Filter the text strings
	$footer_left       = apply_filters( 'equity_footer_left_text', equity_get_option( 'footer-left', 'equity-footer-settings' ) );
	$footer_right      = apply_filters( 'equity_footer_right_text', equity_get_option( 'footer-right', 'equity-footer-settings' ) );
	$footer_disclaimer = apply_filters( 'equity_footer_disclaimer_text', equity_get_option( 'footer-disclaimer', 'equity-footer-settings' ) );

	$output = '
		<div class="columns small-12 large-3 footer-left">' . $footer_left . '</div>
		<div class="columns small-12 large-6 footer-disclaimer">' . $footer_disclaimer . '</div>
		<div class="columns small-12 large-3 footer-right">' . $footer_right . '</div>
	';

	echo apply_filters( 'equity_footer_output', $output, $footer_left, $footer_right, $footer_disclaimer );

}

add_filter( 'equity_footer_scripts', 'do_shortcode' );
add_action( 'wp_footer', 'equity_footer_scripts' );
/**
 * Echo the footer scripts, defined in Theme Settings.
 *
 * Applies the `equity_footer_scripts` filter to the value returns from the footer_scripts option.
 *
 * @since 1.0
 *
 * @uses equity_option() Get theme setting value.
 */
function equity_footer_scripts() {

	echo apply_filters( 'equity_footer_scripts', equity_option( 'footer_scripts' ) );

}
