<?php
/**
 * Equity Framework
 *
 * WARNING: This file is part of the core Equity Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Equity\Layout
 * @author  IDX, LLC
 * @license GPL-2.0+
 * @link    
 */

add_filter( 'content_width', 'equity_content_width', 10, 2 );
/**
 * Filter the content width based on the user selected layout.
 *
 * @since 1.0
 *
 * @uses equity_site_layout() Get the site layout for current context.
 *
 * @param integer $default Default width.
 * @param integer $large   Large width.
 *
 * @return integer Content width.
 */
function equity_content_width( $default, $large ) {

	switch ( equity_site_layout( 0 ) ) {
		case 'full-width-content':
			$width = $large;
			break;
		default:
			$width = $default;
	}

	return $width;

}

add_filter( 'body_class', 'equity_custom_body_class', 15 );
/**
 * Add custom field body class(es) to the body classes.
 *
 * It accepts values from a per-post or per-page custom field, and only outputs when viewing a singular page.
 *
 * @since 1.0
 *
 * @uses equity_get_custom_field() Get custom field value.
 *
 * @param array $classes Existing classes.
 *
 * @return array Amended classes.
 */
function equity_custom_body_class( array $classes ) {

	$new_class = is_singular() ? equity_get_custom_field( '_equity_custom_body_class' ) : null;

	if ( $new_class )
		$classes[] = esc_attr( $new_class );

	return $classes;

}

add_filter( 'body_class', 'equity_header_body_classes' );
/**
 * Add header-* classes to the body class.
 *
 * We can use pseudo-variables in our CSS file, which helps us achieve multiple header layouts with minimal code.
 *
 * @since 1.0
 *
 * @uses equity_get_option() Get theme setting value.
 *
 * @param array $classes Existing classes.
 *
 * @return array Amended classes.
 */
function equity_header_body_classes( array $classes ) {

	if ( 'image' == get_theme_mod('logo_display_type') )
		$classes[] = 'header-image';

	if ( ! is_active_sidebar( 'header-right' ) && ! has_action( 'equity_header_right' ) )
		$classes[] = 'header-full-width';

	return $classes;

}

add_filter( 'body_class', 'equity_layout_body_classes' );
/**
 * Add site layout classes to the body classes.
 *
 * We can use pseudo-variables in our CSS file, which helps us achieve multiple site layouts with minimal code.
 *
 * @since 1.0
 *
 * @uses equity_site_layout() Return the site layout for different contexts.
 *
 * @param array $classes Existing classes.
 *
 * @return array Amended classes.
 */
function equity_layout_body_classes( array $classes ) {

	$site_layout = equity_site_layout();

	if ( $site_layout )
		$classes[] = $site_layout;

	if ( 'boxed' == get_theme_mod('body_layout') ) {
		$classes[] = 'boxed-layout';
	}

	return $classes;

}

add_filter( 'body_class', 'equity_style_selector_body_classes' );
/**
 * Add style selector classes to the body classes.
 *
 * Enables style selector support in child themes, which helps us achieve multiple site styles with minimal code.
 *
 * @since 1.0
 *
 * @uses get_theme_mod() Get theme mod value.
 *
 * @param array $classes Existing classes.
 *
 * @return array Amended classes.
 */
function equity_style_selector_body_classes( array $classes ) {

	$current = get_theme_mod( 'style_selection' );

	if ( $current )
		$classes[] = esc_attr( sanitize_html_class( $current ) );

	return $classes;

}

add_filter( 'body_class', 'equity_cpt_archive_body_class', 15 );
/**
 * Adds a custom class to the custom post type archive body classes.
 *
 * It accepts a value from the archive settings page.
 *
 * @since 1.0
 *
 * @uses equity_has_post_type_archive_support() Check if current CPT has archive support.
 * @uses equity_get_cpt_option()                Get CPT Archive setting.
 *
 * @param array $classes Existing classes.
 *
 * @return array Amended classes.
 */
function equity_cpt_archive_body_class( array $classes ) {

	if ( ! is_post_type_archive() || ! equity_has_post_type_archive_support() )
		return $classes;

	$new_class = equity_get_cpt_option( 'body_class' );

	if ( $new_class )
		$classes[] = esc_attr( sanitize_html_class( $new_class ) );

	return $classes;

}

add_action( 'equity_after_content', 'equity_get_sidebar' );
/**
 * Output the sidebar.php file if layout allows for it.
 *
 * @since 1.0
 * @uses equity_site_layout() Return the site layout for different contexts.
 */
function equity_get_sidebar() {

	$site_layout = equity_site_layout();

	//* Don't load sidebar on pages that don't need it
	if ( 'full-width-content' === $site_layout )
		return;

	if ( is_page() ) {
		get_sidebar('page');
	} else {
		get_sidebar();
	}

}