<?php
/**
 * Equity Framework
 *
 * WARNING: This file is part of the core Equity Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Equity\Loops
 * @author  IDX, LLC
 * @license GPL-2.0+
 * @link    
 */

add_action( 'equity_loop', 'equity_do_loop' );
/**
 * Attach a loop to the `equity_loop` output hook so we can get some front-end output.
 *
 * @since 1.0
 *
 * @uses equity_get_option()       Get theme setting value.
 * @uses equity_get_custom_field() Get custom field value.
 * @uses equity_custom_loop()      Do custom loop.
 * @uses equity_standard_loop()    Do standard loop.
 */
function equity_do_loop() {

	if ( is_page_template( 'page_blog.php' ) ) {
		$include = equity_get_option( 'blog_cat' );
		$exclude = equity_get_option( 'blog_cat_exclude' ) ? explode( ',', str_replace( ' ', '', equity_get_option( 'blog_cat_exclude' ) ) ) : '';
		$paged   = get_query_var( 'paged' ) ? get_query_var( 'paged' ) : 1;

		//* Accepts query args in a custom field named 'query_args'
		$query_args = wp_parse_args(
			equity_get_custom_field( 'query_args' ),
			array(
				'cat'              => $include,
				'category__not_in' => $exclude,
				'showposts'        => equity_get_option( 'blog_cat_num' ),
				'paged'            => $paged,
			)
		);

		equity_custom_loop( $query_args );
	
	// Future feature
	// } elseif ( 'listing' === get_post_type() || is_post_type_archive( 'listing ') ) {
	// 	equity_listing_loop();
	} else {
		equity_standard_loop();
	}

}

/**
 * Standard loop, meant to be executed without modification in most circumstances where content needs to be displayed.
 *
 * It outputs basic wrapping HTML, but uses hooks to do most of its content output like title, content, post information
 * and comments.
 *
 * The action hooks called are:
 *
 *  - `equity_before_while`
 *  - `equity_before_entry`
 *  - `equity_entry_header`
 *  - `equity_before_entry_content`
 *  - `equity_entry_content`
 *  - `equity_after_entry_content`
 *  - `equity_entry_footer`
 *  - `equity_after_entry`
 *  - `equity_after_endwhile`
 *  - `equity_loop_else` (only if no posts were found)
 *
 * @since 1.0
 *
 * @uses equity_attr()        Contextual attributes.
 *
 * @return null 
 */
function equity_standard_loop() {

	if ( have_posts() ) :

		do_action( 'equity_before_while' );
		while ( have_posts() ) : the_post();

			do_action( 'equity_before_entry' );

			printf( '<article %s>', equity_attr( 'entry' ) );

				do_action( 'equity_entry_header' );

				do_action( 'equity_before_entry_content' );
				printf( '<div %s>', equity_attr( 'entry-content' ) );
					do_action( 'equity_entry_content' );
				echo '</div>'; //* end .entry-content
				do_action( 'equity_after_entry_content' );

				do_action( 'equity_entry_footer' );

			echo '</article>';

			do_action( 'equity_after_entry' );

		endwhile; //* end of one post
		do_action( 'equity_after_endwhile' );

	else : //* if no posts exist
		do_action( 'equity_loop_else' );
	endif; //* end loop

}

/**
 * Listing loop, for displaying listing post type in various contexts
 *
 * Similar to standard loop, uses hooks to do most of its content output like title, content, post information
 * and comments.
 *
 * The action hooks called are:
 *
 *  - `equity_before_listing`
 *  - `equity_listing_header`
 *  - `equity_before_listing_content`
 *  - `equity_listing_content`
 *  - `equity_after_listing_content`
 *  - `equity_listing_footer`
 *  - `equity_after_endwhile`
 *  - `equity_loop_else` (only if no posts were found)
 *
 * @since 1.0
 *
 * @uses equity_attr()        Contextual attributes.
 *
 * @return null 
 */
function equity_listing_loop() {

	if ( have_posts() ) : while ( have_posts() ) : the_post();

			do_action( 'equity_before_listing' );

			printf( '<article %s>', equity_attr( 'entry' ) );

				do_action( 'equity_listing_header' );

				do_action( 'equity_before_listing_content' );
				printf( '<div %s>', equity_attr( 'entry-content' ) );
					//do_action( 'equity_listing_content' );
				echo '</div>'; //* end .entry-content
				do_action( 'equity_after_listing_content' );

				do_action( 'equity_listing_footer' );

			echo '</article>';

			do_action( 'equity_after_listing' );

		endwhile; //* end of one post
		do_action( 'equity_after_endwhile' );

	else : //* if no posts exist
		do_action( 'equity_loop_else' );
	endif; //* end loop

}

/**
 * Custom loop, meant to be executed when a custom query is needed.
 *
 * It accepts arguments in query_posts style format to modify the custom `WP_Query` object.
 *
 * It outputs basic wrapping HTML, but uses hooks to do most of its content output like title, content, post information,
 * and comments.
 *
 * The arguments can be passed in via the `equity_custom_loop_args` filter.
 *
 * The action hooks called are the same as {@link equity_standard_loop()}.
 *
 * @since 1.0
 *
 * @uses equity_standard_loop()
 *
 * @global WP_Query $wp_query Query object.
 * @global integer  $more
 *
 * @param array $args Loop configuration.
 */
function equity_custom_loop( $args = array() ) {

	global $wp_query, $more;

	$defaults = array(); //* For forward compatibility
	$args     = apply_filters( 'equity_custom_loop_args', wp_parse_args( $args, $defaults ), $args, $defaults );

	$wp_query = new WP_Query( $args );

	//* Only set $more to 0 if we're on an archive
	$more = is_singular() ? $more : 0;

	equity_standard_loop();

	//* Restore original query
	wp_reset_query();

}

add_action( 'equity_after_entry', 'equity_add_id_to_global_exclude' );
/**
 * Modify the global $_equity_displayed_ids each time a loop iterates.
 *
 * Keep track of what posts have been shown on any given page by adding each ID to a global array, which can be used any
 * time by other loops to prevent posts from being displayed twice on a page.
 *
 * @since 1.0
 *
 * @global array $_equity_displayed_ids Array of displayed post IDs.
 */
function equity_add_id_to_global_exclude() {

	global $_equity_displayed_ids;

	$_equity_displayed_ids[] = get_the_ID();

}
