<?php
/**
 * Equity Framework
 *
 * WARNING: This file is part of the core Equity Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Equity\Menus
 * @author  IDX, LLC
 * @license GPL-2.0+
 * @link    
 */

add_filter( 'nav_menu_link_attributes', 'equity_nav_menu_link_attributes' );
/**
 * Pass nav menu link attributes through attribute parser.
 *
 * Adds nav menu link attributes via the Equity markup API.
 *
 * @since 1.7.3
 *
 * @param array $atts {
 *		The HTML attributes applied to the menu item's link element, empty strings are ignored.
 *
 *		@type string $title Title attribute.
 *		@type string $target Target attribute.
 *		@type string $rel The rel attribute.
 *		@type string $href The href attribute.
 * }
 * @return array Maybe modified menu attributes array.
 */
function equity_nav_menu_link_attributes( $atts ) {

	$atts = equity_parse_attr( 'nav-link', $atts );

	return $atts;

}

add_action( 'after_setup_theme', 'equity_register_nav_menus' );
/**
 * Register the custom menu locations, if theme has support for them.
 *
 * Does the `equity_register_nav_menus` action.
 *
 * @since 1.0
 *
 * @return null Returns early if no Equity menus are supported.
 */
function equity_register_nav_menus() {

	if ( ! current_theme_supports( 'equity-menus' ) )
		return;

	$menus = get_theme_support( 'equity-menus' );

	register_nav_menus( (array) $menus[0] );

	do_action( 'equity_register_nav_menus' );

}

add_action( 'equity_after_header', 'equity_do_main_nav' );
/**
 * Echo the "Main" menu.
 *
 * @since 1.0
 *
 * @uses equity_nav_menu() Display a navigation menu
 * @uses equity_nav_menu_supported() Checks for support of specific nav menu.
 */
function equity_do_main_nav() {

	//* Do nothing if menu not supported
	if ( ! equity_nav_menu_supported( 'main' ) )
		return;

	equity_markup( array(
		'html5'   => '<div class="contain-to-grid"><nav %s data-topbar>',
		'context' => 'nav-main',
	) );
	
	echo '<ul class="title-area"><li class="name"></li><li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li></ul><section class="top-bar-section">';

	$class = 'menu equity-nav-menu menu-main left';

	equity_nav_menu( array(
		'theme_location' => 'main',
		'menu_class'     => $class,
		'walker'         => new Top_Bar_Walker,
	), true );

	echo '</section></nav></div>';

}

add_action( 'equity_before_header', 'equity_open_off_canvas', 10 );
/**
 * Echo the Off Canvas open markup and menu if the current theme supports it and a menu has been assigned to that location.
 *
 * Applies 'equity_off_canvas_side' and 'equity_off_canvas_toggle_text' filters
 * 
 * @since 1.2
 *
 * @uses equity_nav_menu() Display a navigation menu
 */
function equity_open_off_canvas() {

	//* Do nothing if menu not supported
	if ( ! current_theme_supports( 'equity-off-canvas-menu' ) )
		return;
	
	$side        = apply_filters('equity_off_canvas_side', $side = 'left');
	$toggle_text = apply_filters('equity_off_canvas_toggle_text', $toggle_text = '<i class="fas fa-bars"></i> <span class="toggle-text">Menu</span>');
	echo apply_filters( 'equity_off_canvas_open_markup', '<div class="off-canvas-wrap" data-offcanvas>
  			<div class="inner-wrap">
  				<a class="' . $side . '-off-canvas-toggle off-canvas-toggle" href="#" >' . $toggle_text . '</a>
  				<aside class="' . $side . '-off-canvas-menu off-canvas-menu-wrap">', $side, $toggle_text );

	do_action('equity_before_off_canvas_menu');

	if ( has_nav_menu( 'off-canvas' ) ) {
		$class = 'menu equity-nav-menu off-canvas-menu ';
		equity_nav_menu( array(
			'theme_location' => 'off-canvas',
			'menu_class'     => $class,
			'walker'         => new Description_Plus_Icon_Walker,
		), true );
	}

	do_action( 'equity_after_off_canvas_menu' );

	echo '</aside>';

}

add_action( 'equity_after_footer', 'equity_close_off_canvas' );
/**
 * Echo the Off Canvas menu closing markup
 *
 * @since 1.2
 */
function equity_close_off_canvas() {

	//* Do nothing if menu not supported
	if ( ! current_theme_supports( 'equity-off-canvas-menu' ) )
		return;
	
	echo apply_filters( 'equity_off_canvas_close_markup', '<!-- close the off-canvas menu --><a class="exit-off-canvas"></a>
		</div><!-- end .inner-wrap -->
	</div><!-- end .off-canvas-wrap -->' );
}