<?php
/**
 * Equity Framework.
 *
 * WARNING: This file is part of the core Equity Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Equity\Search
 * @author  IDX, LLC
 * @license GPL-2.0+
 * @link    
 */

add_filter( 'get_search_form', 'equity_search_form' );
/**
 * Replace the default search form with a Equity-specific form.
 *
 * The exact output depends on whether the child theme supports HTML5 or not.
 *
 * Applies the `equity_search_text`, `equity_search_button_text`, `equity_search_form_label` and
 * `equity_search_form` filters.
 *
 * @since 0.2.0
 *
 * @uses equity_html5() Check for HTML5 support.
 *
 * @return string HTML markup.
 */
function equity_search_form() {
	$search_text = get_search_query() ? apply_filters( 'the_search_query', get_search_query() ) : apply_filters( 'equity_search_text', __( 'Search this website', 'equity' ) . '&#x02026;' );

	$button_text = apply_filters( 'equity_search_button_text', esc_attr__( 'Search', 'equity' ) );

	$onfocus = "if ('" . esc_js( $search_text ) . "' === this.value) {this.value = '';}";
	$onblur  = "if ('' === this.value) {this.value = '" . esc_js( $search_text ) . "';}";

	//* Filterable label
	$label = apply_filters( 'equity_search_form_label', esc_attr__( 'Search for:', 'equity' ) );

	$value_or_placeholder = ( get_search_query() == '' ) ? 'placeholder' : 'value';

	$form = sprintf( '<form method="get" class="search-form" action="%s" role="search"><span class="screen-reader-text">%s</span><input type="search" name="s" %s="%s" /><input type="submit" value="%s" class="button" /></form>', home_url( '/' ), esc_html( $label ), $value_or_placeholder, esc_attr( $search_text ), esc_attr( $button_text ) );

	return apply_filters( 'equity_search_form', $form, $search_text, $button_text, $label );

}