<?php
/**
 * Equity Framework
 *
 * WARNING: This file is part of the core Equity Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Equity\Framework
 * @author  IDX, LLC
 * @license GPL-2.0+
 * @link    
 */

add_action( 'wp_enqueue_scripts', 'equity_register_scripts' );
/**
 * Register the scripts that Equity will use.
 *
 * @since 1.0
 *
 * @uses EQUITY_JS_URL
 */
function equity_register_scripts() {

	wp_register_script('foundation-mod', EQUITY_JS_URL . '/modernizr.min.js', array(), null, false );
	wp_register_script('foundation-main', EQUITY_JS_URL . '/foundation.min.js', array('jquery'), null, false );
	wp_register_script('foundation-off-canvas', EQUITY_JS_URL . '/foundation.offcanvas.js', array('jquery'), null, true );
	wp_register_script('foundation-app', EQUITY_JS_URL . '/app.js', array('jquery'), null, true );

	//* OWL Carousel script (for listing scroll widget)
	wp_register_script('owl', EQUITY_JS_URL . '/owl.carousel.min.js', array('jquery'), null, true );
	wp_register_script('owl2', EQUITY_JS_URL . '/owl2.carousel.min.js', array('jquery'), null, true );
}

add_action( 'wp_enqueue_scripts', 'equity_load_scripts' );
/**
 * Enqueue the scripts used on the front-end of the site.
 *
 * Includes jquery, mobile navigation, comment-reply, and foundation framework.
 *
 * @since 1.0
 */
function equity_load_scripts() {

	wp_enqueue_script( 'jquery' );
	wp_enqueue_script( 'foundation-mod' );
	wp_enqueue_script( 'foundation-main' );

	//* Load off canvas script
	if ( current_theme_supports( 'equity-off-canvas-menu' ) )
		wp_enqueue_script( 'foundation-off-canvas' );

	//* If a single post or page, threaded comments are enabled, and comments are open
	if ( is_singular() && get_option( 'thread_comments' ) && comments_open() )
		wp_enqueue_script( 'comment-reply' );

	//* load parallax script -- Deprecated as of 1.1.5. DO NOT USE.
	if ( current_theme_supports( 'equity-parallax' ) && ! wp_is_mobile() )
		wp_enqueue_script( 'stellar' );

	//* If theme.js file exists in /lib/js/ folder then enqueue
	if( file_exists( get_stylesheet_directory() . '/lib/js/theme.js' ) )
		wp_enqueue_script( 'equity-theme-js', get_stylesheet_directory_uri() . '/lib/js/theme.js', array('jquery', 'foundation-main'), null, true);
}

add_action( 'admin_enqueue_scripts', 'equity_load_admin_scripts' );
/**
 * Conditionally enqueue the scripts used in the admin.
 *
 * Includes Thickbox, theme preview and a Equity script (actually enqueued in equity_load_admin_js()).
 *
 * @since 1.0
 *
 * @uses equity_load_admin_js() Enqueues the custom script and localizations used in the admin.
 * @uses equity_is_menu_page()  Check that we're targeting a specific Equity admin page.
 *
 * @param string $hook_suffix Admin page identifier.
 */
function equity_load_admin_scripts( $hook_suffix ) {

	//* If we're on a Equity admin screen
	if ( equity_is_menu_page( 'equity' ) )
		equity_load_admin_js();

}

/**
 * Enqueues the custom script used in the admin, and localizes several strings or values used in the scripts.
 *
 * Applies the `equity_toggles` filter to toggleable admin settings, so plugin developers can add their own without
 * having to recreate the whole setup.
 *
 * @since 1.0
 *
 * @uses EQUITY_JS_URL
 */
function equity_load_admin_js() {

	wp_enqueue_script( 'equity_admin_js', EQUITY_JS_URL . "/admin.js", array( 'jquery' ), null, true );

	$strings = array(
		'categoryChecklistToggle' => __( 'Select / Deselect All', 'equity' ),
		'saveAlert'               => __('The changes you made will be lost if you navigate away from this page.', 'equity'),
		'confirmReset'            => __( 'Are you sure you want to reset?', 'equity' ),
	);

	wp_localize_script( 'equity_admin_js', 'equity_L10n', $strings );

	$toggles = array(
		// Checkboxes - when checked, show extra settings
		// 
		// Select toggles
	);

	wp_localize_script( 'equity_admin_js', 'equity_toggles', apply_filters( 'equity_toggles', $toggles ) );

}
