<?php
/**
 * Equity Framework
 *
 * WARNING: This file is part of the core Equity Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Equity\Shortcodes
 * @author  IDX, LLC
 * @license GPL-2.0+
 * @link    
 */

add_shortcode( 'footer_copyright', 'equity_footer_copyright_shortcode' );
/**
 * Adds the visual copyright notice.
 *
 * Supported shortcode attributes are:
 *   after (output after notice, default is empty string),
 *   before (output before notice, default is empty string),
 *   copyright (copyright notice, default is copyright character like (c) ),
 *   first(year copyright first applies, default is empty string).
 *
 * If the 'first' attribute is not empty, and not equal to the current year, then
 * output will be formatted as first-current year (e.g. 1998-2020).
 * Otherwise, output is just given as the current year.
 *
 * Output passes through 'equity_footer_copyright_shortcode' filter before returning.
 *
 * @since 1.0
 *
 * @param array|string $atts Shortcode attributes. Empty string if no attributes.
 * @return string Shortcode output
 */
function equity_footer_copyright_shortcode( $atts ) {

	$defaults = array(
		'after'     => '',
		'before'    => '',
		'copyright' => '&#x000A9;',
		'first'     => '',
	);
	$atts = shortcode_atts( $defaults, $atts, 'footer_copyright' );

	$output = $atts['before'] . $atts['copyright'] . '&nbsp;';

	if ( '' != $atts['first'] && date( 'Y' ) != $atts['first'] )
		$output .= $atts['first'] . '&#x02013;';

	$output .= date( 'Y' ) . $atts['after'];

	return apply_filters( 'equity_footer_copyright_shortcode', $output, $atts );

}

add_shortcode( 'footer_equity_link', 'equity_footer_equity_link_shortcode' );
/**
 * Adds link to the Equity Framework site
 *
 * Supported shortcode attributes are:
 *   after (output after link, default is empty string),
 *   before (output before link, default is empty string).
 *
 * Output passes through 'equity_footer_equity_link_shortcode' filter before returning.
 *
 * @since 1.0
 *
 * @param array|string $atts Shortcode attributes. Empty string if no attributes.
 * @return string Shortcode output
 */
function equity_footer_equity_link_shortcode( $atts ) {

	$footer_copy_array = array(
        'WordPress Real Estate Themes',
        'WordPress Themes for Real Estate Agents',
        'Real Estate WordPress Themes',
        'WordPress Themes with IDX',
        'Real Estate Themes for WordPress',
        'WordPress Real Estate Templates',
        'WordPress Real Estate Theme Framework',
    );

    $footer_copy = array_rand($footer_copy_array);

	$defaults = array(
		'after'  => '',
		'before' => '',
		'url'    => 'http://equityframework.com',
	);
	$atts = shortcode_atts( $defaults, $atts, 'footer_equity_link' );

	$output = $atts['before'] . '<a href="' . esc_url( $atts['url'] ) . '" title="' . $footer_copy_array[$footer_copy] . '">Equity Framework</a>' . $atts['after'];

	return apply_filters( 'equity_footer_equity_link_shortcode', $output, $atts );

}

add_shortcode( 'footer_loginout', 'equity_footer_loginout_shortcode' );
/**
 * Adds admin login / logout link.
 *
 * Support shortcode attributes are:
 *   after (output after link, default is empty string),
 *   before (output before link, default is empty string),
 *   redirect (path to redirect to on login, default is empty string).
 *
 * Output passes through 'equity_footer_loginout_shortcode' filter before returning.
 *
 * @since 1.0
 *
 * @param array|string $atts Shortcode attributes. Empty string if no attributes.
 * @return string Shortcode output
 */
function equity_footer_loginout_shortcode( $atts ) {

	$defaults = array(
		'after'    => '',
		'before'   => '',
		'redirect' => '',
	);
	$atts = shortcode_atts( $defaults, $atts, 'footer_loginout' );

	if ( ! is_user_logged_in() )
		$link = '<a href="' . esc_url( wp_login_url( $atts['redirect'] ) ) . '">' . __( 'Log in', 'equity' ) . '</a>';
	else
		$link = '<a href="' . esc_url( wp_logout_url( $atts['redirect'] ) ) . '">' . __( 'Log out', 'equity' ) . '</a>';

	$output = $atts['before'] . apply_filters( 'loginout', $link ) . $atts['after'];

	return apply_filters( 'equity_footer_loginout_shortcode', $output, $atts );

}
