<?php
/**
 * Equity Framework
 *
 * WARNING: This file is part of the core Equity Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Equity\Shortcodes
 * @author  IDX, LLC
 * @license GPL-2.0+
 * @link    
 */

include_once IMPRESS_IDX_DIR . 'idx/widgets/impress-widget-helper.php';

add_shortcode('lead_login', 'lead_login_shortcode');
function lead_login_shortcode() {
	$_idx = new Equity_Idx_Api;
	$widget = sprintf('
		<form action="%sajax/userlogin.php" method="post" target="" name="leadLoginForm">
			<input type="hidden" name="action" value="login">
			<input type="hidden" name="loginWidget" value="true">
			<label for="bb-IDX-widgetEmail">Email Address:</label>
			<input id="bb-IDX-widgetEmail" type="text" name="email" placeholder="Enter your email address">
			<input id="bb-IDX-widgetPassword" type="hidden" name="password" value="">
			<input id="bb-IDX-widgetLeadLoginSubmit" type="submit" name="login" value="Log In">
		</form>', $_idx->subdomain_url());

	return $widget;
}

add_shortcode('property_showcase', 'property_showcase_shortcode');
function property_showcase_shortcode($atts = array()) {

	$_idx = new Equity_Idx_Api;

	$output = '<div class="property-showcase shortcode">';

	extract(shortcode_atts(array(
		'max'           => 4,
		'use_rows'      => 1,
		'num_per_row'   => 4,
		'show_image'    => 1,
		'order'         => 'high-low',
		'property_type' => 'featured',
		'saved_link_id' => '',
		'agentID'       => ''
	), $atts ) );

	if ( ($property_type) == 'savedlink') {
		$properties = $_idx->saved_link_properties($saved_link_id);
		$output .= '<!-- Saved Link ID: ' . $saved_link_id . ' -->';
	} else {
		$properties = $_idx->client_properties($property_type);
		$output .= '';
	}

	if ( empty($properties) || (isset($properties) && $properties === 'No results returned') ) {
		return 'No properties found';
	}

	$total = count($properties);
	$count = 0;

	$column_class = '';

	if ( 1 == $use_rows ) {

		// Max of four columns
		$number_columns = ( $num_per_row > 4 ) ? 4 : (int)$num_per_row;

		// column class
		switch ($number_columns) {
			case 0:
				$column_class = 'columns small-12 large-12';
				break;
			case 1:
				$column_class = 'columns small-12 large-12';
				break;
			case 2:
				$column_class = 'columns small-12 medium-6 large-6';
				break;
			case 3:
				$column_class = 'columns small-12 medium-4 large-4';
				break;
			case 4:
				$column_class = 'columns small-12 medium-3 large-3';
				break;
		}
	}

	// sort low to high
	usort($properties, array($_idx, 'price_cmp'));

	if ( 'high-low' == $order ) {
		$properties = array_reverse($properties);
	}

	foreach ($properties as $prop) {

		if ( isset( $agentID, $prop['userAgentID'] ) && ! empty( $agentID ) ) {
			if ( $agentID !== (int) $prop['userAgentID'] ) {
				continue;
			}
		}

		if ( !empty($max) && $count == $max ) {
			$output .= '</div><!-- end .property-showcase.shortcode -->';
			return $output;
		}

		$prop_image_url = ( isset($prop['image']['0']['url']) ) ? $prop['image']['0']['url'] : 'https://s3.amazonaws.com/mlsphotos.idxbroker.com/defaultNoPhoto/noPhotoFull.png';

		if ( 1 == $use_rows && $count == 0 && $max != '1' ) {
			$output .= '<div class="row">';
		}

		if(empty($prop['propStatus'])) {
			$prop['propStatus'] = '';
		}

		$count++;

		if(isset($prop['disclaimer']) && !empty($prop['disclaimer'])) {
			foreach($prop['disclaimer'] as $disclaimer) {
				if(in_array('widget', $disclaimer)) {
					$disclaimer_text = $disclaimer['text'];
					$disclaimer_logo = $disclaimer['logoURL'];
				}
			}
		}

		if(isset($prop['courtesy']) && !empty($prop['courtesy'])) {
			foreach($prop['courtesy'] as $courtesy) {
				if(in_array('widget', $courtesy)) {
					$courtesy_text = $courtesy['text'];
				}
			}
		}

		// Get URL and add suffix if one exists
		if ( isset($prop['fullDetailsURL']) ) {
			$url = $prop['fullDetailsURL'];
		} else {
			$url = $_idx->details_url() . '/' . $prop['detailsURL'];
		}

		if ( has_filter( 'equity_idx_showcase_property_url_suffix' ) ) {
			$url = $url . apply_filters( 'equity_idx_showcase_property_url_suffix', $suffix = '', $prop, $_idx );
		}

		if ( 1 == $show_image ) {
			$output .= sprintf('<div class="showcase-property %12$s">
					<a href="%3$s" class="showcase-photo">
						<img src="%4$s" alt="%5$s" title="%5$s" />
						<span class="price">%1$s</span>
						<span class="status">%2$s</span>
					</a>
					<a href="%3$s">
						<p class="address">
							<span class="street">%6$s</span>
							<span class="cityname">%7$s</span>,
							<span class="state"> %8$s</span>
						</p>
					</a>
					<p class="beds-baths-sqft">
						<span class="beds">%9$s Beds</span>
						<span class="baths">%10$s Baths</span>
						<span class="sqft">%11$s Sq Ft</span>
					</p>
					<div class="disclaimer">%13$s %14$s %15$s</div>
				</div>',
				price_selector( $prop ),
				$prop['propStatus'],
				$url,
				$prop_image_url,
				esc_html($prop['remarksConcat']),
				empty( $prop['address'] ) ? '' : $prop['address'],
				empty( $prop['cityName'] ) ? '' : $prop['cityName'],
				empty( $prop['state'] ) ? '' : $prop['state'],
				empty( $prop['bedrooms'] ) ? '' : $prop['bedrooms'],
				empty( $prop['totalBaths'] ) ? '' : $prop['totalBaths'],
				empty( $prop['sqFt'] ) ? '' : $prop['sqFt'],
				$column_class,
				(isset($disclaimer_text)) ? '<p style="display: block !important; visibility: visible !important;">' . $disclaimer_text . '</p>' : '',
				(isset($disclaimer_logo)) ? '<img class="logo" src="' . $disclaimer_logo . '" style="opacity: 1 !important; position: static !important;" />' : '',
				(isset($courtesy_text)) ? '<p class="courtesy" style="display: block !important; visibility: visible !important;">' . $courtesy_text . '</p>' : ''
			);
		} else {
			$output .= sprintf(
				'<li class="showcase-property-list %9$s">
					<a href="%2$s">
						<p>
							<span class="price">%1$s</span>
							<span class="address">
								<span class="street">%3$s</span>
								<span class="cityname">%4$s</span>,
								<span class="state"> %5$s</span>
							</span>
							<span class="beds-baths-sqft">
								<span class="beds">%6$s Beds</span>
								<span class="baths">%7$s Baths</span>
								<span class="sqft">%8$s Sq Ft</span>
							</span>
						</p>
					</a>
				</li>',
				price_selector( $prop ),
				$url,
				empty( $prop['address'] ) ? '' : $prop['address'],
				empty( $prop['cityName'] ) ? '' : $prop['cityName'],
				empty( $prop['state'] ) ? '' : $prop['state'],
				empty( $prop['bedrooms'] ) ? '' : $prop['bedrooms'],
				empty( $prop['totalBaths'] ) ? '' : $prop['totalBaths'],
				empty( $prop['sqFt'] ) ? '' : $prop['sqFt'],
				$column_class
			);
		}

		if ( 1 == $use_rows && $count != 1 ) {

			// close a row if..
			// num_per_row is a factor of count OR
			// count is equal to the max number of listings to show OR
			// count is equal to the total number of listings available
			if ( $count % $num_per_row == 0 || $count == $total || $count == $max ) {
				$output .= '</div> <!-- .row -->';
			}

			// open a new row if..
			// num per row is a factor of count AND
			// count is not equal to max AND
			// count is not equal to total
			if ( $count % $num_per_row == 0 && $count != $max && $count != $total ) {
				$output .= '<div class="row">';
			}
		}
	}

	$output .= '</div><!-- end .property-showcase.shortcode -->';

	return $output;

}

add_shortcode('property_carousel', 'property_carousel_shortcode');
function property_carousel_shortcode($atts = array()) {

	$_idx = new Equity_Idx_Api;

	extract(shortcode_atts(array(
		'max'           => 4,
		'display'       => 3,
		'autoplay'      => 1,
		'order'         => 'high-low',
		'property_type' => 'featured',
		'saved_link_id' => '',
		'agentID'       => ''
	), $atts ) );

	wp_enqueue_style( 'owl-css' );
	wp_enqueue_script( 'owl' );

	$prev_link = apply_filters( 'idx_listing_carousel_prev_link', $idx_listing_carousel_prev_link_text = __( '<i class=\"fas fa-chevron-circle-left\"></i><span>Prev</span>', 'equity' ) );
	$next_link = apply_filters( 'idx_listing_carousel_next_link', $idx_listing_carousel_next_link_text = __( '<i class=\"fas fa-chevron-circle-right\"></i><span>Next</span>', 'equity' ) );

	if ( ($property_type) == 'savedlink') {
		$properties = $_idx->saved_link_properties($saved_link_id);
		//$output .= '<!-- Saved Link ID: ' . $saved_link_id . ' -->';
	} else {
		$properties = $_idx->client_properties($property_type);
		//$output .= '';
	}

	if ( empty($properties) || (isset($properties) && $properties === 'No results returned') ) {
		return 'No properties found';
	}

	// sort low to high
	usort($properties, array($_idx, 'price_cmp') );

	if ( 'high-low' == $order ) {
		$properties = array_reverse($properties);
	}

	if( $autoplay == 1 ) {
		$autoplay_param = 'autoPlay: true,';
	} else {
		$autoplay_param = '';
	}

	if($display === "1") {
		$output = '
		<script>
		jQuery(function( $ ){
			jQuery(".equity-listing-carousel-' . $display . '").owlCarousel({
				singleItem: true,
				' . $autoplay_param . '
				navigation: true,
				navigationText: ["' . $prev_link . '", "' . $next_link . '"],
				pagination: false,
				lazyLoad: true,
				addClassActive: true,
				itemsScaleUp: true
			});
		});
		</script>
		';
	} else {
		$output = '
		<script>
		jQuery(function( $ ){
			jQuery(".equity-listing-carousel-' . $display . '").owlCarousel({
				items: ' . $display . ',
				' . $autoplay_param . '
				navigation: true,
				navigationText: ["' . $prev_link . '", "' . $next_link . '"],
				pagination: false,
				lazyLoad: true,
				addClassActive: true,
				itemsScaleUp: true
			});
		});
		</script>
		';
	}

	$count = 0;

	$output .= sprintf('<div class="equity-idx-carousel equity-listing-carousel-%s carousel-shortcode">', $display);

	if ( ($property_type) == 'savedlink') {
		$output .= '<!-- Saved Link ID: ' . $saved_link_id . ' -->';
	}

	foreach ($properties as $prop) {
		if ( isset( $agentID, $prop['userAgentID'] ) && ! empty( $agentID ) ) {
			if ( $agentID !== (int) $prop['userAgentID'] ) {
				continue;
			}
		}

		if ( !empty($max) && $count == $max ) {
			$output .= '</div><!-- end .equity-listing-carousel -->';
			return $output;
		}

		$prop_image_url = ( isset($prop['image']['0']['url']) ) ? $prop['image']['0']['url'] : 'https://s3.amazonaws.com/mlsphotos.idxbroker.com/defaultNoPhoto/noPhotoFull.png';

		$count++;

		if(isset($prop['disclaimer']) && !empty($prop['disclaimer'])) {
			foreach($prop['disclaimer'] as $disclaimer) {
				if(in_array('widget', $disclaimer)) {
					$disclaimer_text = $disclaimer['text'];
					$disclaimer_logo = $disclaimer['logoURL'];
				}
			}
		}

		if(isset($prop['courtesy']) && !empty($prop['courtesy'])) {
			foreach($prop['courtesy'] as $courtesy) {
				if(in_array('widget', $courtesy)) {
					$courtesy_text = $courtesy['text'];
				}
			}
		}

		// Get URL and add suffix if one exists
		if ( isset($prop['fullDetailsURL']) ) {
			$url = $prop['fullDetailsURL'];
		} else {
			$url = $_idx->details_url() . '/' . $prop['detailsURL'];
		}

		if ( has_filter( 'equity_idx_carousel_property_url_suffix' ) ) {
			$url = $url . apply_filters( 'equity_idx_carousel_property_url_suffix', $suffix = '', $prop, $_idx );
		}

		$output .= sprintf(
			'<div class="carousel-property">
				<a href="%2$s" class="carousel-photo">
					<img class="lazyOwl" data-src="%3$s" alt="%4$s" title="%4$s" />
					<span class="price">%1$s</span>
				</a>
				<a href="%2$s">
					<p class="address">
						<span class="street">%5$s</span>
						<span class="cityname">%6$s</span>,
						<span class="state"> %7$s</span>
					</p>
				</a>
				<p class="beds-baths-sqft">
					<span class="beds">%8$s Beds</span>
					<span class="baths">%9$s Baths</span>
					<span class="sqft">%10$s Sq Ft</span>
				</p>
				<div class="disclaimer">%11$s %12$s %13$s</div>
			</div>',
			price_selector( $prop ),
			$url,
			$prop_image_url,
			esc_html($prop['remarksConcat']),
			empty( $prop['address'] ) ? '' : $prop['address'],
			empty( $prop['cityName'] ) ? '' : $prop['cityName'],
			empty( $prop['state'] ) ? '' : $prop['state'],
			empty( $prop['bedrooms'] ) ? '' : $prop['bedrooms'],
			empty( $prop['totalBaths'] ) ? '' : $prop['totalBaths'],
			empty( $prop['sqFt'] ) ? '' : $prop['sqFt'],
			(isset($disclaimer_text)) ? '<p style="display: block !important; visibility: visible !important;">' . $disclaimer_text . '</p>' : '',
			(isset($disclaimer_logo)) ? '<img class="logo" src="' . $disclaimer_logo . '" style="opacity: 1 !important; position: static !important;" />' : '',
			(isset($courtesy_text)) ? '<p class="courtesy" style="display: block !important; visibility: visible !important;">' . $courtesy_text . '</p>' : ''
		);
	}

	$output .= '</div><!-- end .equity-listing-carousel -->';

	return $output;
}

add_shortcode('city_links', 'city_links_shortcode');
function city_links_shortcode($atts = array()) {

	$_idx = new Equity_Idx_Api;

	extract(shortcode_atts(array(
		'city_list'      => 'combinedActiveMLS',
		'mls'            => 'a000',
		'use_columns'    => 1,
		'number_columns' => 4
	), $atts ) );

	$city_links = $_idx->city_list_links($city_list, $mls, $use_columns, $number_columns);

	if (false == $city_links) {
		return 'City list ID or MLS ID not found';
	}
	$city_links .= '<style>.city-list-links ul {margin-left: 0;}</style>';
	return $city_links;
}

/**
 * Adds link to IDX sitemap from pulled from Equity_Idx_Api::system_link_url
 *
 * Support shortcode attributes are:
 *   link_text (text to use for link).
 *
 * @since 1.3
 *
 * @return string Shortcode output
 */
add_shortcode( 'idx_sitemap', 'equity_footer_sitemap_shortcode' );
function equity_footer_sitemap_shortcode( $atts ) {
	$_idx = new Equity_Idx_Api;

	extract( shortcode_atts( array(
		'link_text' => 'Listings Sitemap',
	), $atts ) );

	$idx_feed_uri = $_idx->system_link_url( 'XML Sitemap' );

	return sprintf( '<a class="idx-sitemap" href="%s">%s</a>', $idx_feed_uri, $link_text );

}

/**
 * Add support for Shortcake (Shortcode UI)
 *
 * @see  https://github.com/fusioneng/Shortcake
 * @since 1.5
 */
if ( function_exists( 'shortcode_ui_register_for_shortcode' ) ) {
	//* Lead Login
	shortcode_ui_register_for_shortcode(
		'lead_login',
		array(
			'label'         => 'Lead Login',
			'listItemImage' => 'dashicons-admin-network',
		)
	);

	//* Lead Signup
	shortcode_ui_register_for_shortcode(
		'lead_signup',
		array(
			'label'         => 'Lead Signup',
			'listItemImage' => 'dashicons-admin-users',
			'attrs' => array(
                array(
                    'label' => 'Require Phone?',
                    'attr'  => 'phone',
                    'type'  => 'radio',
                    'value' => 0,
                    'options' => array(
                    		1 => 'Yes',
                    		0 => 'No',
                    ),
                ),
            ),
		)
	);

	//* Property Showcase
	//$saved_links = $this->_idx->saved_links();
	shortcode_ui_register_for_shortcode(
		'property_showcase',
		array(
			'label'         => 'Property Showcase',
			'listItemImage' => 'dashicons-admin-home',
			'attrs' => array(
                array(
                    'label' => 'Max Number of Listings',
                    'attr'  => 'max',
                    'type'  => 'number',
                    'value' => 8,
                ),
                array(
                    'label' => 'Use Rows',
                    'attr'  => 'use_rows',
                    'type'  => 'radio',
                    'value' => 1,
                    'options' => array(
                    		1 => 'Yes',
                    		0 => 'No',
                    ),
                ),
                array(
                    'label' => 'Number per row',
                    'attr'  => 'num_per_row',
                    'type'  => 'number',
                    'value' => 4,
                ),
                array(
                    'label' => 'Order',
                    'attr'  => 'order',
                    'type'  => 'select',
                    'value' => 'high-low',
                    'options' => array(
                		'high-low' => 'High to Low',
                		'low-high' => 'Low to High',
                    ),
                ),
                array(
                    'label' => 'Show Image',
                    'attr'  => 'show_image',
                    'type'  => 'radio',
                    'value' => 1,
                    'options' => array(
                    		1 => 'Yes',
                    		0 => 'No',
                    ),
                ),
                array(
                    'label' => 'Property Type',
                    'attr'  => 'property_type',
                    'type'  => 'select',
                    'value' => 'featured',
                    'options' => array(
                		'featured'     => 'Featured',
                		'soldpending'  => 'Sold/Pending',
                		'supplemental' => 'Supplemental',
                		'savedlink'    => 'Saved Link',
                    ),
                ),
                array(
                    'label' => 'Saved Link ID',
                    'attr'  => 'saved_link_id',
                    'type'  => 'text',
                    'value' => '',
                ),
            ),
		)
	);
	
	//* Property Carousel
	shortcode_ui_register_for_shortcode(
		'property_carousel',
		array(
			'label'         => 'Property Carousel',
			'listItemImage' => 'dashicons-admin-home',
			'attrs' => array(
                array(
                    'label' => 'Max Number of Listings',
                    'attr'  => 'max',
                    'type'  => 'number',
                    'value' => 4,
                ),
                array(
                    'label' => 'Number to Display without scrolling',
                    'attr'  => 'display',
                    'type'  => 'number',
                    'value' => 3,
                ),
                array(
                    'label' => 'Order',
                    'attr'  => 'order',
                    'type'  => 'select',
                    'value' => 'high-low',
                    'options' => array(
                		'high-low' => 'High to Low',
                		'low-high' => 'Low to High',
                    ),
                ),
                array(
                    'label' => 'Autoplay',
                    'attr'  => 'autoplay',
                    'type'  => 'radio',
                    'value' => 1,
                    'options' => array(
                    		1 => 'Yes',
                    		0 => 'No',
                    ),
                ),
                array(
                    'label' => 'Property Type',
                    'attr'  => 'property_type',
                    'type'  => 'select',
                    'value' => 'featured',
                    'options' => array(
                		'featured'     => 'Featured',
                		'soldpending'  => 'Sold/Pending',
                		'supplemental' => 'Supplemental',
                		'savedlink'    => 'Saved Link',
                    ),
                ),
                array(
                    'label' => 'Saved Link ID',
                    'attr'  => 'saved_link_id',
                    'type'  => 'text',
                    'value' => '',
                ),
            ),
		)
	);

	//* City Links
	shortcode_ui_register_for_shortcode(
		'city_links',
		array(
			'label'         => 'City Links',
			'listItemImage' => 'dashicons-editor-ul',
			'attrs' => array(
                array(
                    'label' => 'City List',
                    'attr'  => 'city_list',
                    'type'  => 'text',
                    'value' => 'combinedActiveMLS',
                ),
                array(
                    'label' => 'MLS ID',
                    'attr'  => 'mls',
                    'type'  => 'text',
                    'value' => 'a000',
                ),
                array(
                    'label' => 'Use Columns?',
                    'attr'  => 'use_columns',
                    'type'  => 'radio',
                    'value' => 1,
                    'options' => array(
                    		1 => 'Yes',
                    		0 => 'No',
                    ),
                ),
                array(
                    'label' => 'Number of Columns',
                    'attr'  => 'number_columns',
                    'type'  => 'select',
                    'value' => 4,
                    'options' => array(
                		2 => '2',
                		3 => '3',
                		4 => '4',
                    ),
                ),
            ),
		)
	);
}