<?php
/**
 * Equity Framework.
 *
 * WARNING: This file is part of the core Equity Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Equity\Widgets
 * @author  IDX, LLC
 * @license GPL-2.0+
 * @link    
 *  Notes: This takes the WordPress Custom Menu Widget and adds a call to a custom walker that will display the menu link description.
 *  Based on: https://gist.github.com/FStop/3882358 from Gabriel Luethje (@FStop)
 */

// Create the widget. This is basically a copy of the WP code, taken from /wp-includes/default_widgets.php
class EQUITY_Menu_Widget extends WP_Widget {

  function __construct() {
	$widget_ops = array( 'description' => __('Adds a custom menu that outputs the link title, description, and optional icon.', 'equity'), 'customize_selective_refresh' => true );
	parent::__construct( 'nav_menu_desc', __('Equity - Custom Menu', 'equity'), $widget_ops );
  }
 
  function widget($args, $instance) {
	// Get menu

	$nav_menu = ! empty( $instance['nav_menu'] ) ? wp_get_nav_menu_object( $instance['nav_menu'] ) : false;

	if ( !$nav_menu )
	  return;

	$instance['title'] = apply_filters( 'widget_title', empty( $instance['title'] ) ? '' : $instance['title'], $instance, $this->id_base );

	echo $args['before_widget'];

	if ( !empty($instance['title']) )
	  echo $args['before_title'] . $instance['title'] . $args['after_title'];

	wp_nav_menu( array( 'fallback_cb' => '', 'menu' => $nav_menu, 'walker' => new Description_Plus_Icon_Walker) ); // calling the new walker so we have descriptions

	echo $args['after_widget'];

	wp_reset_query();
  }
 
  function update( $new_instance, $old_instance ) {
	$instance['title'] = strip_tags( stripslashes($new_instance['title']) );
	$instance['nav_menu'] = (int) $new_instance['nav_menu'];
	return $instance;
  }
 
  function form( $instance ) {
	$title = isset( $instance['title'] ) ? $instance['title'] : '';
	$nav_menu = isset( $instance['nav_menu'] ) ? $instance['nav_menu'] : '';

	// Get menus
	$menus = wp_get_nav_menus( array( 'orderby' => 'name' ) );

	// If no menus exists, direct the user to go and create some.
	if ( !$menus ) {
	  echo '<p>'. sprintf( __('No menus have been created yet. <a href="%s">Go create some</a>!'), admin_url('nav-menus.php') ) .'</p>';
	  return;
	}
	?>
	<p>
	  <label for="<?php echo $this->get_field_id('title'); ?>"><?php _e('Title:', 'equity') ?></label>
	  <input type="text" class="widefat" id="<?php echo $this->get_field_id('title'); ?>" name="<?php echo $this->get_field_name('title'); ?>" value="<?php echo $title; ?>" />
	</p>
	<p>
	  <label for="<?php echo $this->get_field_id('nav_menu'); ?>"><?php _e('Select Menu:', 'equity'); ?></label>
	  <select id="<?php echo $this->get_field_id('nav_menu'); ?>" name="<?php echo $this->get_field_name('nav_menu'); ?>">
	<?php
	  foreach ( $menus as $menu ) {
		$selected = $nav_menu == $menu->term_id ? ' selected="selected"' : '';
		echo '<option'. $selected .' value="'. $menu->term_id .'">'. $menu->name .'</option>';
	  }
	?>
	  </select>
	</p>
	<?php
  }
 
}