<?php
/**
 * Equity Framework.
 *
 * WARNING: This file is part of the core Equity Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * Adds a Featured Post responsive carousel widget
 *
 * @package Equity\Widgets
 * @author  IDX, LLC
 * @license GPL-2.0+
 * @link    
 */
class Equity_Featured_Page_Carousel extends WP_Widget {

	function __construct() {
		$widget_ops  = array( 'classname' => 'equity-post-carousel equity-page-carousel clearfix owlcarousel', 'description' => __( 'Display featured posts in a responsive carousel', 'equity' ), 'customize_selective_refresh' => true );
		$control_ops = array( 'width' => 300, 'height' => 350 );
		parent::__construct( 'equity-page-carousel', __( 'Equity - Featured Post Carousel', 'equity' ), $widget_ops, $control_ops );
	}

	function widget( $args, $instance ) {
		
		$instance = wp_parse_args( $instance, array(
			'title'				=> '',
			'post_type'         => 'page',
			'page_id'           => array(),
			'show_title'        => 0,
			'show_content'      => 'excerpt',
			'content_limit'     => '',
			'more_text'         => __( 'Continue reading...', 'equity' ),
			'posts_per_widget'	=> 3,
			'image_size'		=> 'thumbnail',
			'autoplay'          => 1
		) );

		wp_enqueue_style( 'owl2-css' );
		wp_enqueue_script( 'owl2' );

		$prev_link = apply_filters( 'equity_page_carousel_prev_link', $equity_page_carousel_prev_link_text = __( '<i class=\"fas fa-chevron-circle-left\"></i><span>Prev</span>', 'equity' ) );
		$next_link = apply_filters( 'equity_page_carousel_next_link', $equity_page_carousel_next_link_text = __( '<i class=\"fas fa-chevron-circle-right\"></i><span>Next</span>', 'equity' ) );

		extract( $args );

		// Maybe add autoplay param.
		if( $instance['autoplay'] ) {
			$autoplay = 'autoplay: true,';
		} else {
			$autoplay = '';
		}

		// Get posts per carousel view.
		$posts_per_carousel = $instance['posts_per_widget'];

		echo $before_widget;

			if ( ! empty( $instance['title'] ) ) {
				echo $before_title . apply_filters( 'widget_title', $instance['title'], $instance, $this->id_base ) . $after_title;
			}

			$query_args = array(
				'post_type'	=> $instance['post_type'],
				'orderby'   => 'post__in',
				'nopaging'  => true
			);

			if ( ! is_array( $instance['page_id'] ) ) {
				$IDs = explode( ',', str_replace( ' ', '', $instance['page_id'] ) );
			} else {
				$IDs = $instance['page_id'];
			}
			
			if ( 1 !== count( $IDs ) ) {
				echo '<script>
					var owljq=jQuery.noConflict();
					owljq(document).ready(function(){
						owljq(".equity-page-carousel-' . $posts_per_carousel . '").owlCarousel({
							items: ' . $posts_per_carousel . ',
							' . $autoplay . '
							nav: true,
							navText: ["' . $prev_link . '", "' . $next_link . '"],
							loop: true,
							lazyLoad: true,
							addClassActive: true,
							itemsScaleUp: true,
							addClassActive: true,
							itemsScaleUp: true,
							responsiveClass:true,
							navContainerClass: "owl-controls owl-nav",
							responsive:{
								0:{
									items: 1,
									nav: true,
									margin: 0 
								},
								450:{
									items: ' . round( $posts_per_carousel / 2 ) . '
								},
								800:{
									items: ' . $posts_per_carousel . '
								}
							}
						});
					});
					</script>
				';
			}

			$query_args['post__in'] = $IDs;

			$featured_page_widget_query = new WP_Query( $query_args );

			echo '<div class="page-carousel equity-page-carousel-' . $instance['posts_per_widget'] . ' owl-carousel owl-theme">';

			global $post;

			if ( $featured_page_widget_query->have_posts() ) : while ( $featured_page_widget_query->have_posts() ) : $featured_page_widget_query->the_post();

				$thumbnail_src = wp_get_attachment_image_src( get_post_thumbnail_id($post->ID), $instance['image_size'] );
				$loop = sprintf( '<div class="page-widget-thumb"><a href="%s" class="page-image-link"><img class="owl-lazy lazyOwl" data-src="%s" /></a>', get_permalink(), $thumbnail_src[0] );

			$title = get_the_title() ? get_the_title() : __( '(no title)', 'equity' );

			$loop .= sprintf( '<header class="entry-header"><h2 class="entry-title"><a href="%s">%s</a></h2></header>', get_permalink(), esc_html( $title ) );


			if ( ! empty( $instance['show_content'] ) ) {

				$loop .= '<div class="entry-content">';

				if ( 'excerpt' == $instance['show_content'] ) {
					$loop .= get_the_excerpt();
				}
				elseif ( 'content-limit' == $instance['show_content'] ) {
					$loop .= get_the_content_limit( (int) $instance['content_limit'], esc_html( $instance['more_text'] ) );
				}
				else {

					global $more;

					$orig_more = $more;
					$more = 0;

					$loop .= get_the_content( esc_html( $instance['more_text'] ) );

					$more = $orig_more;

				}

				$loop .= '</div>';

			}

			printf( '<article class="page-%s"><div class="page-wrap">%s</div></article>', $post->ID, apply_filters( 'equity_page_carousel_widget_loop', $loop ) );

			endwhile; endif;

			echo '</div><!-- .equity-page-carousel -->';
			wp_reset_postdata();

		echo $after_widget;
		
	}

	/**
	 * Sanitize widget form values as they are saved.
	 *
	 * @see WP_Widget::update()
	 *
	 * @param array $new_instance Values just sent to be saved.
	 * @param array $old_instance Previously saved values from database.
	 * @return array Updated safe values to be saved.
	 */
	function update( $new_instance, $old_instance ) {
		$instance = array();
		$instance['title']            = strip_tags( $new_instance['title'] );
		$instance['post_type']        = $new_instance['post_type'];
		$instance['page_id']          = esc_sql($new_instance['page_id']);
		$instance['show_content']     = $new_instance['show_content'];
		$instance['content_limit']    = $new_instance['content_limit'];
		$instance['more_text']        = $new_instance['more_text'];
		$instance['posts_per_widget'] = (int) $new_instance['posts_per_widget'];
		$instance['image_size'] 	  = strip_tags($new_instance['image_size'] );
		$instance['autoplay']         = (int) $new_instance['autoplay'];

		return $instance;
	}

	function form( $instance ) {
		wp_enqueue_script( 'equity-admin-widgets', EQUITY_JS_URL . '/admin-widgets.js', array( 'jquery', 'select2' ), false, true );
		wp_enqueue_script( 'select2', 'https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.min.js', array( 'jquery' ), null, true );
		wp_enqueue_script( 'jquery-ui-sortable' );
		wp_enqueue_style( 'select2-css', 'https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css' );
		
		// Pre-select pages if set.
		if ( isset( $instance['page_id'] ) && ! empty( $instance['page_id'] ) ) {
			$page_ids = json_encode( ( ! is_array( $instance['page_id'] ) ) ? explode( ',', $instance['page_id'] ) : $instance['page_id'] );
			$select2_defaults = "$('select#" . $this->get_field_id( 'page_id' ) . "').val(" . $page_ids . ");";
			wp_add_inline_script( 'equity-admin-widgets', $select2_defaults, 'after' );
		}

		$instance = wp_parse_args( $instance, array(
			'title'				=> '',
			'post_type'         => 'page',
			'page_id'           => array(),
			'show_content'      => 'excerpt',
			'content_limit'     => '',
			'more_text'         => __( 'Continue reading...', 'equity' ),
			'posts_per_widget'	=> 3,
			'image_size'		=> 'thumbnail',
			'autoplay'          => 1
		) );
		?>
		
		<p>
			<label for="<?php echo $this->get_field_id('title'); ?>"><?php _e( 'Title:', 'equity' ); ?></label>
			<input type="text" id="<?php echo $this->get_field_id('title'); ?>" name="<?php echo $this->get_field_name('title'); ?>" value="<?php echo esc_attr( $instance['title'] ); ?>" class="widefat"/>
		</p>

		<p>
			<label for="<?php echo $this->get_field_id( 'post_type' ); ?>"><?php _e( 'Post Type', 'equity' ); ?>:</label>
			<select id="<?php echo $this->get_field_id( 'post_type' ); ?>" class="featured-carousel-post-type" name="<?php echo $this->get_field_name( 'post_type' ); ?>">
				<?php echo $this->get_post_types_options( array('idx-wrapper', 'attachment'), $instance['post_type'] ); ?>
			</select>
			<strong class="warning-refresh" style="display: none;">Save to refresh list of posts to select from!</strong>
		</p>

		<p>
			<label for="<?php echo $this->get_field_id( 'page_id' ); ?>"><?php _e( 'Posts to display:', 'equity' ); ?></label>
			<select id="<?php echo $this->get_field_id( 'page_id' ); ?>" class="featured-carousel-posts" name="<?php echo $this->get_field_name( 'page_id' ); ?>[]" multiple="multiple" style="width: 100%;">
				
				<?php echo $this->get_posts_of_type( $instance['post_type'], $this->get_field_id( 'page_id' ), $this->get_field_name( 'page_id' ), $instance['page_id'] ); ?>
			</select>
		</p>

		<p>
			<label for="<?php echo $this->get_field_id( 'show_content' ); ?>"><?php _e( 'Content Type', 'equity' ); ?>:</label>
			<select id="<?php echo $this->get_field_id( 'show_content' ); ?>" name="<?php echo $this->get_field_name( 'show_content' ); ?>">
				<option value="content" <?php selected( 'content', $instance['show_content'] ); ?>><?php _e( 'Show Content', 'equity' ); ?></option>
				<option value="excerpt" <?php selected( 'excerpt', $instance['show_content'] ); ?>><?php _e( 'Show Excerpt', 'equity' ); ?></option>
				<option value="content-limit" <?php selected( 'content-limit', $instance['show_content'] ); ?>><?php _e( 'Show Content Limit', 'equity' ); ?></option>
				<option value="" <?php selected( '', $instance['show_content'] ); ?>><?php _e( 'No Content', 'equity' ); ?></option>
			</select>
			<br />
			<label for="<?php echo $this->get_field_id( 'content_limit' ); ?>"><?php _e( 'Limit content to', 'equity' ); ?>
				<input type="text" id="<?php echo $this->get_field_id( 'content_limit' ); ?>" name="<?php echo $this->get_field_name( 'content_limit' ); ?>" value="<?php echo esc_attr( intval( $instance['content_limit'] ) ); ?>" size="3" />
				<?php _e( 'characters', 'equity' ); ?>
			</label>
		</p>

		<p>
			<label for="<?php echo $this->get_field_id( 'more_text' ); ?>"><?php _e( 'More Text (if applicable)', 'equity' ); ?>:</label>
			<input type="text" id="<?php echo $this->get_field_id( 'more_text' ); ?>" name="<?php echo $this->get_field_name( 'more_text' ); ?>" value="<?php echo esc_attr( $instance['more_text'] ); ?>" />
		</p>

		<p>
			<label for="<?php echo $this->get_field_id( 'image_size' ); ?>"><?php _e( 'Image Size', 'equity' ); ?>:</label>
			<select id="<?php echo $this->get_field_id( 'image_size' ); ?>" class="featured-page-image-size-selector" name="<?php echo $this->get_field_name( 'image_size' ); ?>">
				<option value="thumbnail">thumbnail (<?php echo absint( get_option( 'thumbnail_size_w' ) ); ?>x<?php echo absint( get_option( 'thumbnail_size_h' ) ); ?>)</option>
				<?php
				$sizes = equity_get_additional_image_sizes();
				foreach ( (array) $sizes as $name => $size )
					echo '<option value="' . esc_attr( $name ) . '" ' . selected( $name, $instance['image_size'], FALSE ) . '>' . esc_html( $name ) . ' (' . absint( $size['width'] ) . 'x' . absint( $size['height'] ) . ')</option>';
				?>
			</select>
		</p>

		<?php

		printf(
			'<p>%s <input type="text" name="%s" value="%s" size="3" /></p>',
			__( 'Initial number of posts to display without scrolling', 'equity' ),
			$this->get_field_name('posts_per_widget'),
			esc_attr( $instance['posts_per_widget'] )
		);

		printf(
			'<p><label for="%s">%s</label> <input type="checkbox" name="%s" value="1" %s /></p>',
			$this->get_field_id('autoplay'),
			__( 'Autoplay?', 'equity' ),
			$this->get_field_name('autoplay'),
			checked( $instance['autoplay'], true, false )
		);

		?>

		<?php
	}

	/**
	 * Returns the available post types as select options.
	 * @param  array  $exclusions Post type slugs to exclude.
	 * @param  string $post_type  The instance post type.
	 * @return string             The post types wrapped in option tags.
	 */
	function get_post_types_options( $exclusions, $post_type ) {
		$args = array(
			'public' => true,
		);
		$types = get_post_types( $args );
		if ( is_array( $exclusions ) ) {
			foreach ( $exclusions as $exclude ) {
				unset( $types[ $exclude ] );
			}
		}
		$output = '';
		foreach ( $types as $type ) {
			$output .= '<option value="' . $type . '" ' . selected( $post_type, $type, 0 ) . '>' . ucfirst( $type ) . '</option>';
		}
		return $output;
	}

	/**
	 * Return posts of the selected type.
	 *
	 * @param  string $type [description]
	 * @return [type]       [description]
	 */
	function get_posts_of_type( $type = 'page', $id, $name, $instance ) {

		$args = array(
			'post_type'      => $type,
			'posts_per_page' => -1,

		);

		$posts = get_posts( $args );

		if ( $posts ) {
			$output = '';
			foreach ( $posts as $post ) {

				if ( in_array( $post->ID, (array) $instance ) ) {
					$selected = 'selected="selected"';
				} else {
					$selected = '';
				}

				$output .= '<option value="' . $post->ID . '" id="' . $id . '" name="' . $name . '" ' . $selected . '>' . get_the_title( $post->ID ) . '</option>';
			}

			return $output;
		}

		return false;
	}

}
