<?php
/**
 * Equity Framework
 *
 * WARNING: This file is part of the core Equity Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Equity\Widgets
 * @author  IDX, LLC
 * @license GPL-2.0+
 * @link    
 */

/**
 * Equity Icon Box widget class.
 *
 * @since 1.0
 *
 * @package Equity\Widgets
 */
class EQUITY_Icon_Box extends WP_Widget {

	/**
	 * Holds widget settings defaults, populated in constructor.
	 *
	 * @var array
	 */
	protected $defaults;

	/**
	 * Constructor. Set the default widget options and create widget.
	 *
	 * @since 1.0
	 */
	function __construct() {

		$this->defaults = array(
			'title'          => 'Call to Action',
			'type'           => 1,
			'newtab'         => 0,
			'icon'           => 'fa-user',
			'url'            => '',
			'content'        => 'Click on my link!',
		);

		$widget_ops = array(
			'classname'   => 'equity-icon-box',
			'description' => __( 'Displays icon box call to action.', 'equity' ),
			'customize_selective_refresh' => true,
		);

		$control_ops = array(
			'id_base' => 'equity-icon-box',
			'width'   => 200,
			'height'  => 250,
		);

		parent::__construct( 'equity-icon-box', __( 'Equity - Icon Box', 'equity' ), $widget_ops, $control_ops );

	}

	/**
	 * Echo the widget content.
	 *
	 * @since 1.0
	 *
	 * @global WP_Query $wp_query Query object.
	 * @global integer  $more
	 *
	 * @param array $args Display arguments including before_title, after_title, before_widget, and after_widget.
	 * @param array $instance The settings for the particular instance of the widget
	 */
	function widget( $args, $instance ) {

		wp_enqueue_style( 'font-awesome-5.8.2' );

		global $wp_query;

		//* Merge with defaults
		$instance = wp_parse_args( (array) $instance, $this->defaults );

		echo $args['before_widget'];

		//* Set up the heading
		if ( ! empty( $instance['title'] ) ) {
			$heading = '<h4>' . apply_filters( 'widget_title', $instance['title'], $instance, $this->id_base ) . '</h4>';
		} else {
			$heading = '';
		}

		//* Set up the content
		if ( ! empty( $instance['content'] ) ) {
			$content = '<p>' . $instance['content'] . '</p>';
		} else {
			$content = '';
		}

		$classes = 'ae-iconbox type-' . $instance['type'];

		$target = ( true == $instance['newtab'] ) ? 'target="_blank"' : '';

		if ( ! empty( $instance['url'] ) ) {
			echo '<div class="' . $classes . '">
				<div class="icon"><a href="' . $instance['url'] . '" ' . $target . '><i class="fas ' . $instance['icon'] . '"></i></a></div>
				<a href="' . $instance['url'] . '" ' . $target . '>' . $heading . '</a>
				' . $content . '
			</div><!-- ae-iconbox type-' . $instance['type'] . ' -->';
		} else {
			echo '<div class="' . $classes . '">
				<div class="icon"><i class="fas ' . $instance['icon'] . '"></i></div>
				' . $heading . '
				' . $content . '
			</div><!-- ae-iconbox type-' . $instance['type'] . ' -->';
		}

		echo $args['after_widget'];
	}

	/**
	 * Update a particular instance.
	 *
	 * This function should check that $new_instance is set correctly.
	 * The newly calculated value of $instance should be returned.
	 * If "false" is returned, the instance won't be saved/updated.
	 *
	 * @since 1.0
	 *
	 * @param array $new_instance New settings for this instance as input by the user via form()
	 * @param array $old_instance Old settings for this instance
	 * @return array Settings to save or bool false to cancel saving
	 */
	function update( $new_instance, $old_instance ) {

		$new_instance['title']     = sanitize_text_field( $new_instance['title'] );
		$new_instance['type']      = (int) $new_instance['type'];
		$new_instance['newtab']    = (bool) $new_instance['newtab'];
		$new_instance['icon']      = sanitize_text_field( $new_instance['icon'] );
		$new_instance['url']       = esc_url( $new_instance['url'] );
		$new_instance['content']   = sanitize_textarea_field( $new_instance['content'] );
		return $new_instance;

	}

	/**
	 * Echo the settings update form.
	 *
	 * @since 1.0
	 *
	 * @param array $instance Current settings
	 */
	function form( $instance ) {

		//* Merge with defaults
		$instance = wp_parse_args( (array) $instance, $this->defaults );

		?>
		<p>
			<label for="<?php echo $this->get_field_id( 'title' ); ?>"><?php _e( 'Heading', 'equity' ); ?>:</label>
			<input type="text" id="<?php echo $this->get_field_id( 'title' ); ?>" name="<?php echo $this->get_field_name( 'title' ); ?>" value="<?php echo esc_attr( $instance['title'] ); ?>" class="widefat" />
		</p>

		<p>
			<label for="<?php echo $this->get_field_id( 'type' ); ?>"><?php _e( 'Type', 'equity' ); ?>:</label>
			<select id="<?php echo $this->get_field_id( 'type' ); ?>" name="<?php echo $this->get_field_name( 'type' ); ?>">
				<option value="1" <?php selected( 1, $instance['type'] ); ?>><?php _e( 'Type 1', 'equity' ); ?></option>
				<option value="2" <?php selected( 2, $instance['type'] ); ?>><?php _e( 'Type 2', 'equity' ); ?></option>
				<option value="3" <?php selected( 3, $instance['type'] ); ?>><?php _e( 'Type 3', 'equity' ); ?></option>
				<option value="4" <?php selected( 4, $instance['type'] ); ?>><?php _e( 'Type 4', 'equity' ); ?></option>
				<option value="5" <?php selected( 5, $instance['type'] ); ?>><?php _e( 'Type 5', 'equity' ); ?></option>
			</select>
		</p>

		<p>
			<input id="<?php echo $this->get_field_id( 'newtab' ); ?>" type="checkbox" name="<?php echo $this->get_field_name( 'newtab' ); ?>" value="1" <?php checked( $instance['newtab'] ); ?> />
			<label for="<?php echo $this->get_field_id( 'newtab' ); ?>"><?php _e( 'Open in New Tab?', 'equity' ); ?></label>
		</p>

		<p>
			<label for="<?php echo $this->get_field_id( 'icon' ); ?>"><?php _e( 'Icon Class (<a href="https://fontawesome.com/cheatsheet" target="_blank">list of available icon classes</a>)', 'equity' ); ?>:</label>
			<input type="text" id="<?php echo $this->get_field_id( 'icon' ); ?>" name="<?php echo $this->get_field_name( 'icon' ); ?>" value="<?php echo esc_attr( $instance['icon'] ); ?>" class="widefat" />
		</p>

		<p>
			<label for="<?php echo $this->get_field_id( 'url' ); ?>"><?php _e( 'URL to link to (optional)', 'equity' ); ?>:</label>
			<input type="text" id="<?php echo $this->get_field_id( 'url' ); ?>" name="<?php echo $this->get_field_name( 'url' ); ?>" value="<?php echo esc_attr( $instance['url'] ); ?>" class="widefat" />
		</p>

		<p>
			<label for="<?php echo $this->get_field_id( 'content' ); ?>"><?php _e( 'Description', 'equity' ); ?>:</label>
			<textarea type="text" id="<?php echo $this->get_field_id( 'content' ); ?>" name="<?php echo $this->get_field_name( 'content' ); ?>" value="<?php echo esc_attr( $instance['content'] ); ?>" class="widefat" cols="100" rows="3" ><?php echo esc_attr( $instance['content'] ); ?></textarea>
		</p>
		<?php

	}

}
