<?php
/**
 * Equity Framework
 *
 * WARNING: This file is part of the core Equity Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Equity\Widgets
 * @author  IDX, LLC
 * @license GPL-2.0+
 * @link    
 */

//* Include widget class files
require_once( EQUITY_WIDGETS_DIR . '/featured-post-widget.php' );
require_once( EQUITY_WIDGETS_DIR . '/featured-page-widget.php' );
require_once( EQUITY_WIDGETS_DIR . '/custom-menu-widget.php' );
require_once( EQUITY_WIDGETS_DIR . '/featured-listing-scroller.php' );
require_once( EQUITY_WIDGETS_DIR . '/featured-post-carousel.php' );
require_once( EQUITY_WIDGETS_DIR . '/icon-box-widget.php' );

add_action( 'widgets_init', 'equity_load_widgets' );
/**
 * Register widgets for use in the Equity theme.
 *
 * @since 1.0
 */
function equity_load_widgets() {

	register_widget( 'EQUITY_Featured_Page' );
	register_widget( 'EQUITY_Featured_Post' );
	register_widget( 'EQUITY_Featured_Page_Carousel' );
	register_widget( 'EQUITY_Menu_Widget' );
	register_widget( 'EQUITY_Icon_Box' );

	if(function_exists('wp_listings_init')) {
		register_widget( 'EQUITY_Featured_Listings_Scroller' );
	}

}

add_action( 'load-themes.php', 'equity_remove_default_widgets_from_top_header_left' );
/**
 * Temporary function to work around the default widgets that get added to
 * Top Header Left when switching themes.
 *
 * The $defaults array contains a list of the IDs of the widgets that are added
 * to the first sidebar in a new default install. If this exactly matches the
 * widgets in Top Header Left after switching themes, then they are removed.
 *
 * This works around a perceived WP problem for new installs.
 *
 * If a user amends the list of widgets in the first sidebar before switching to
 * a Equity child theme, then this function won't do anything.
 *
 * @since 1.0
 *
 * @return null Return early if not just switched to a new theme.
 */
function equity_remove_default_widgets_from_top_header_left() {

	//* Some tomfoolery for a faux activation hook
	if ( ! isset( $_REQUEST['activated'] ) || 'true' !== $_REQUEST['activated'] )
		return;

	$widgets  = get_option( 'sidebars_widgets' );
	$defaults = array( 0 => 'search-2', 1 => 'recent-posts-2', 2 => 'recent-comments-2', 3 => 'archives-2', 4 => 'categories-2', 5 => 'meta-2', );

	if ( isset( $widgets['top-header-left'] ) && $defaults === $widgets['top-header-left'] ) {
		$widgets['top-header-left'] = array();
		update_option( 'sidebars_widgets', $widgets );
	}

}
