<?php
/**
 * Equity Framework
 *
 * WARNING: This file is part of the core Equity Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Equity\Admin
 * @author  IDX, LLC
 * @license GPL-2.0+
 * @link    
 */

/**
 * Register a new admin page, providing content and corresponding menu item for the CPT Archive Settings page.
 *
 * @package Equity\Admin
 */
class EQUITY_Admin_CPT_Archive_Settings extends EQUITY_Admin_Boxes {

	/**
	 * Post type object.
	 *
	 * @var \stdClass
	 */
	protected $post_type;

	/**
	 * Create an archive settings admin menu item and settings page for relevant custom post types.
	 *
	 * @since 1.0
	 *
	 * @uses EQUITY_CPT_ARCHIVE_SETTINGS_FIELD_PREFIX Settings field key prefix.
	 * @uses \EQUITY_admin::create()                  Create admin menu and settings page.
	 *
	 * @param object $post_type the WP_Post_Type object in WP 4.6+.
	 */
	public function __construct( $post_type ) {
		$this->post_type = $post_type;

		$page_id = 'equity-cpt-archive-' . $this->post_type->name;

		$menu_ops = array(
			'submenu' => array (
				'parent_slug' => 'edit.php?post_type=' . $this->post_type->name,
				'page_title'  => apply_filters( 'equity_cpt_archive_settings_page_label', __( 'Archive Settings', 'equity' ) ),
				'menu_title'  => apply_filters( 'equity_cpt_archive_settings_menu_label', __( 'Archive Settings', 'equity' ) ),
				'capability'  => 'edit_theme_options',
			)
		);

		//* Handle non-top-level CPT menu items
		if ( is_string( $this->post_type->show_in_menu ) ) {
			$menu_ops['submenu']['parent_slug'] = $this->post_type->show_in_menu;
			$menu_ops['submenu']['menu_title']  = apply_filters( 'equity_cpt_archive_settings_label', $this->post_type->labels->name . ' ' . __( 'Archive', 'equity' ) );
			$menu_ops['submenu']['menu_position']  = $this->post_type->menu_position;
		}

		$page_ops = array(); //* use defaults

		$settings_field = EQUITY_CPT_ARCHIVE_SETTINGS_FIELD_PREFIX . $this->post_type->name;

		$default_settings = apply_filters(
			'equity_cpt_archive_settings_defaults',
			array(
				'headline'    => '',
				'intro_text'  => '',
				'layout'      => '',
				'body_class'  => '',
			)
		);

		$this->create( $page_id, $menu_ops, $page_ops, $settings_field, $default_settings );

		add_action( 'equity_settings_sanitizer_init', array( $this, 'sanitizer_filters' ) );
	}

	/**
	 * Register each of the settings with a sanitization filter type.
	 *
	 * @since 1.0
	 *
	 * @uses equity_add_option_filter() Assign filter to array of settings.
	 *
	 * @see \EQUITY_Settings_Sanitizer::add_filter()
	 */
	public function sanitizer_filters() {

		equity_add_option_filter(
			'no_html',
			$this->settings_field,
			array(
				'headline',
				'body_class',
			)
		);
		equity_add_option_filter(
			'safe_html',
			$this->settings_field,
			array(
				'intro_text',
			)
		);
	}

	/**
 	 * Register meta boxes on the CPT Archive pages.
 	 *
 	 * Some of the meta box additions are dependent on certain theme support or user capabilities.
 	 *
 	 * The 'equity_cpt_archives_settings_metaboxes' action hook is called at the end of this function.
 	 *
 	 * @since 1.0
 	 *
 	 * @see \EQUITY_Admin_CPT_Archives_Settings::archive_box() Callback for Archive box.
 	 * @see \EQUITY_Admin_CPT_Archives_Settings::layout_box()  Callback for Layout box.
	 */
	public function metaboxes() {
		add_meta_box( 'equity-cpt-archives-settings', __( 'Archive Settings', 'equity' ), array( $this, 'archive_box' ), $this->pagehook, 'main' );
		add_meta_box( 'equity-cpt-archives-layout-settings', __( 'Layout Settings', 'equity' ), array( $this, 'layout_box' ), $this->pagehook, 'main' );

		do_action( 'equity_cpt_archives_settings_metaboxes', $this->pagehook );
	}

	/**
	 * Callback for Archive Settings meta box.
	 *
	 * @since 1.0
	 *
	 * @uses \EQUITY_Admin::get_field_id()    Construct full field id.
	 * @uses \EQUITY_Admin::get_field_name()  Construct full field name.
	 * @uses \EQUITY_Admin::get_field_value() Retrieve value of key under $this->settings_field.
	 *
	 * @see \EQUITY_Admin_Settings::metaboxes() Register meta boxes.
	 */
	public function archive_box() {
		?>
		<p><?php printf( __( 'View the <a href="%s">%s archive</a>.', 'equity' ), get_post_type_archive_link( $this->post_type->name ), $this->post_type->name ); ?></p>

		<p><label for="<?php $this->field_id( 'headline' ); ?>"><b><?php _e( 'Archive Headline', 'equity' ); ?></b></label></p>
		<p><input class="large-text" type="text" name="<?php $this->field_name( 'headline' ); ?>" id="<?php $this->field_id( 'headline' ); ?>" value="<?php echo esc_attr( $this->get_field_value( 'headline' ) ); ?>" /></p>
		<p class="description"><?php _e( 'Leave empty if you do not want to display a headline.', 'equity' ); ?></p>

		<p><label for="<?php $this->field_id( 'intro_text' ); ?>"><b><?php _e( 'Archive Intro Text', 'equity' ); ?></b></label></p>
		<p><textarea class="widefat" rows="5" cols="30" name="<?php $this->field_name( 'intro_text' ); ?>" id="<?php $this->field_id( 'intro_text' ); ?>"><?php echo esc_textarea( $this->get_field_value( 'intro_text' ) ); ?></textarea></p>
		<p class="description"><?php _e( 'Leave empty if you do not want to display any intro text.', 'equity' ); ?></p>
		<?php
	}

	/**
	 * Callback for Layout Settings meta box.
	 *
	 * @since 1.0
	 *
	 * @uses \EQUITY_Admin::get_field_id()    Construct full field id.
	 * @uses \EQUITY_Admin::get_field_name()  Construct full field name.
	 * @uses \EQUITY_Admin::get_field_value() Retrieve value of key under $this->settings_field.
	 * @uses equity_layout_selector()         Display layout selector.
	 *
	 * @see \EQUITY_Admin_Settings::metaboxes() Register meta boxes.
	 */
	public function layout_box() {
		$layout = $this->get_field_value( 'layout' );

		?>
		<div class="equity-layout-selector">
			<p><input type="radio" class="default-layout" name="<?php $this->field_name( 'layout' ); ?>" id="default-layout" value="" <?php checked( $layout, '' ); ?> /> <label class="default" for="default-layout"><?php printf( __( 'Default Layout set in <a href="%s">Customize</a>', 'equity' ), esc_url( admin_url( 'customize.php' ) ) ); ?></label></p>

			<p><?php equity_layout_selector( array( 'name' => $this->get_field_name( 'layout' ), 'selected' => $layout, 'type' => 'site' ) ); ?></p>
		</div>

		<br class="clear" />

		<p><label for="<?php $this->field_id( 'body_class' ); ?>"><b><?php _e( 'Custom Body Class', 'equity' ); ?></b></label></p>
		<p><input class="large-text" type="text" name="<?php $this->field_name( 'body_class' ); ?>" id="<?php $this->field_id( 'body_class' ); ?>" value="<?php echo esc_attr( $this->get_field_value( 'body_class' ) ); ?>" /></p>
		<?php
	}

	/**
	 * Add contextual help content for the archive settings page.
	 *
	 * @since 1.0
	 *
	 * @todo Populate this contextual help method.
	 */
	public function help() {
		$screen = get_current_screen();
		$archive_help =
			'<h3>' . __( 'Archive Settings', 'equity' ) . '</h3>' .
			'<p>' . __( 'The Archive Headline sets the title seen on the archive page', 'equity' ) . '</p>' .
			'<p>' . __( 'The Archive Intro Text sets the text before the archive entries to introduce the content to the viewer.', 'equity' ) . '</p>';

		$screen->add_help_tab(
			array(
				'id'      => $this->pagehook . '-archive',
				'title'   => __( 'Archive Settings', 'equity' ),
				'content' => $archive_help,
			)
		);

		$layout_help =
			'<h3>' . __( 'Layout Settings', 'equity' ) . '</h3>' .
			'<p>'  . __( 'This lets you select the layout for the archive page. On most of the child themes you\'ll see these options:', 'equity' ) . '</p>' .
			'<ul>' .
				'<li>' . __( 'Content Sidebar', 'equity' ) . '</li>' .
				'<li>' . __( 'Sidebar Content', 'equity' ) . '</li>' .
				'<li>' . __( 'Full Width Content', 'equity' ) . '</li>' .
			'</ul>' .
			'<p>'  . __( 'These options can be extended or limited by the child theme.', 'equity' ) . '</p>' .
			'<p>'  . __( 'The Custom Body Class adds a class to the body tag in the HTML to allow CSS modification exclusively for this post type\'s archive page.', 'equity' ) . '</p>';

		$screen->add_help_tab(
			array(
				'id'      => $this->pagehook . '-layout',
				'title'   => __( 'Layout Settings', 'equity' ),
				'content' => $layout_help,
			)
		);
	}
}
