<?php
/**
 * Equity Framework
 *
 * WARNING: This file is part of the core Equity Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * Add custom CSS panel if post type support is there
 * 
 * @package Equity\Admin
 * @author  IDX, LLC
 * @license GPL-2.0+
 * @link   
 * 
 * @uses EQUITY_JS_URL
 * 
 * @since 1.0
 */

$custom_css_support = get_theme_support( 'equity-custom-css' );
if ( !$custom_css_support )
    return;

/**
 * Add custom css editor scripts, admin pages, and output custom css to <head>
 */
add_action( 'admin_enqueue_scripts', 'equity_custom_css_scripts' );
add_action( 'admin_menu', 'equity_custom_css_admin_page' );
add_action( 'admin_init', 'equity_register_custom_css_setting' );

/**
 * Loads ACE editor scripts for custom CSS edits
 */
function equity_custom_css_scripts( $hook ) {
    if ( 'equity_page_equity_custom_css_admin_page_content' == $hook ) {
        wp_enqueue_script( 'ace_code_highlighter_js', EQUITY_JS_URL . '/ace/ace.js', '', '1.0.0', true );
        wp_enqueue_script( 'ace_mode_js', EQUITY_JS_URL . '/ace/mode-css.js', array( 'ace_code_highlighter_js' ), '1.0.0', true );
        wp_enqueue_script( 'custom_css_js', EQUITY_JS_URL . '/custom-css.js', array( 'jquery', 'ace_code_highlighter_js' ), '1.0.0', true );
    }
}

/**
 * Adds ACE editor page to admin
 */
function equity_custom_css_admin_page() {
    add_submenu_page( 'equity', __( 'Custom CSS', 'equity' ),  __( 'Custom CSS', 'equity' ), 'edit_theme_options', 'equity_custom_css_admin_page_content', 'equity_custom_css_admin_page_content' );
}

/**
 * Registers custom_css setting
 */
function equity_register_custom_css_setting() {
    register_setting( 'custom_css', 'custom_css', 'equity_custom_css_validation');
}

/**
 * Custom CSS admin page content
 */
function equity_custom_css_admin_page_content() {
    // The default message that will appear
    $custom_css_default = __( '/*
Welcome to the Equity Framework Custom CSS editor!
 
Please add all your custom CSS here and avoid modifying the core theme files, since that\'ll make upgrading the theme problematic. Your custom CSS will be loaded after the theme\'s stylesheets, which means that your rules will take precedence. Just add your CSS here for what you want to change, you don\'t need to copy all the theme\'s style.css content. (p.s. you can delete this text :)
*/', 'equity' );
    $custom_css = get_option( 'custom_css', $custom_css_default );
    ?>
    <div class="wrap">
        <div id="icon-themes" class="icon32"></div>
        <h2><?php _e( 'Custom CSS', 'equity' ); ?></h2>
        <?php if ( ! empty( $_GET['settings-updated'] ) ) echo '<div id="message" class="updated"><p><strong>' . __( 'Custom CSS updated.', 'equity' ) . '</strong></p></div>'; ?>
 
        <form id="custom_css_form" method="post" action="options.php" style="margin-top: 15px;">
 
            <?php settings_fields( 'custom_css' ); ?>
 
            <div id="custom_css_container">
                <div name="custom_css" id="custom_css" style="border: 1px solid #DFDFDF; -moz-border-radius: 3px; -webkit-border-radius: 3px; border-radius: 3px; width: 100%; height: 400px; position: relative;"></div>
            </div>
 
            <textarea id="custom_css_textarea" name="custom_css" style="display: none;"><?php echo $custom_css; ?></textarea>
            <p><input type="submit" class="button-primary" value="<?php _e( 'Save Changes', 'equity' ) ?>" /></p>
        </form>
    </div>
<?php
}

/**
 * Validate code
 */
function equity_custom_css_validation( $input ) {
    if ( ! empty( $input['custom_css'] ) )
        $input['custom_css'] = trim( $input['custom_css'] );
    return $input;
}