<?php
/**
 * Equity Framework
 *
 * WARNING: This file is part of the core Equity Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * This file adds a Footer Settings Page under the Equity tab.
 * 
 * @package Equity\Admin
 * @author  IDX, LLC
 * @license GPL-2.0+
 * @link   
 */
if ( !class_exists( 'CMB2' ) )
	require_once EQUITY_CLASSES_DIR . '/cmb2/init.php';

class EQUITY_Footer_Settings extends EQUITY_Admin_Form {

	/**
 	 * Option key, and option page slug
 	 * @var string
 	 */
	private $key = 'equity-footer-settings';

	/**
 	 * Options page metabox id
 	 * @var string
 	 */
	private $metabox_id = 'equity_footer_settings_metabox';

	/**
	 * Options Page title
	 * @var string
	 */
	protected $title = '';

	/**
	 * Options Page hook
	 * @var string
	 */
	protected $options_page = 'equity_page_equity-footer-settings';

	/**
	 * Constructor
	 * @since 1.5.3
	 */
	public function __construct() {
		# Set it as a child to 'equity', and define the menu and page titles
		$menu_ops = array(
			'submenu' => array(
				'parent_slug' => 'equity',
				'page_title'  => __( 'Footer Content', 'equity' ),
				'menu_title'  => __( 'Footer Settings', 'equity' ),
			)
		);

		$page_ops = array(); //* use defaults

		$settings_field = 'equity-footer-settings';

		# Set the default values
		$default_settings = array();

		# Create the Admin Page
		$this->create( $this->key, $menu_ops, $page_ops, $settings_field, $default_settings);
	}

	/**
	 * Initiate our hooks
	 * @since 1.5.3
	 */
	public function hooks() {
		add_action( 'cmb2_init', array( $this, 'add_footer_settings_metabox' ) );
		add_action( 'equity_settings_sanitizer_init', array( $this, 'sanitization_filters' ) );
		add_filter( 'cmb2_get_metabox_form_format', array( $this, 'form_format' ) );
	}

	/**
	 * Filter the CMB2 form format
	 * @since 1.5.3
	 */
	function form_format($form_format) {
		$form_format = '<form class="cmb-form" method="post" id="%1$s" enctype="multipart/form-data" encoding="multipart/form-data"><input type="hidden" name="object_id" value="%2$s"><input type="submit" name="submit-cmb" value="Save" class="button-primary">%3$s<input type="submit" name="submit-cmb" value="%4$s" class="button-primary"></form>';
		return $form_format;
	}

	/**
	 * Do the CMB2 form
	 * @since 1.5.3
	 */
	public function form() {
		cmb2_metabox_form( $this->metabox_id, $this->key );
	}

	/**
	 * Admin page markup. Mostly handled by CMB2
	 * @since  1.5.3
	 */
	public function admin() {
		?>
		<style>.cmb-td {width: 60%;} .cmb-row {border-bottom: 1px solid #ccc;}</style>
		<div class="wrap equity-form cmb2-options-page <?php echo $this->key; ?>">
			<h2><?php echo esc_html( get_admin_page_title() ); ?></h2>
			<?php do_action( "{$this->pagehook}_settings_page_form", $this->pagehook ); ?>
		</div>
		<?php
	}

	/**
	 * Set up Help Tab
	 */
	function help() {
	 	$screen = get_current_screen();

		$screen->add_help_tab( array(
			'id'      => 'equity-footer-help',
			'title'   => __( 'Equity Footer', 'equity' ),
			'content' => __( '<p>Use the editors below to customize the content of the footer left, footer right, and disclaimer.</p><hr>
								<h2>Equity footer shortcodes:</h2>
									<ul>
										<h3>IDX Sitemap</h3>
										<strong style="color: ">[idx_sitemap]</strong>
										<p>No additional parameters.</p>
										<h3>Footer Login/Log Out link</h3>
										<strong>[footer_loginout]</strong>
										<p>Text link to log in or logged out based on current logged in status.</p>
										<p>Supported shortcode parameters are:
											<li>after (output after link, default is none)</li>
											<li>before (output before link, default is none)</li>
											<li>redirect (path to redirect to on login, default is none)</li>
										</p>
										<h3>Footer Copyright</h3>
										<strong>[footer_copyright]</strong>
										<p>Displays copyright info with symbol and current year.</p>
										<p>
										Supported shortcode attributes are:
											<li>after (output after notice, default is none)</li>
											<li>before (output before notice, default is none)</li>
											<li>copyright (copyright notice, default is copyright character &copy; )</li>
											<li>first (year copyright first applies, default is none and displays current year)</li>
										</p>
									</ul>
								</p>', 'equity'
						),
		) );
	}

	/**
	 * Set up Sanitization Filters
	 * @since 1.0.0
	 *
	 * See /lib/classes/sanitization.php for all available filters.
	 */
	function sanitization_filters() {

		equity_add_option_filter( 'safe_html', $this->key,
			array(
				'footer-left',
				'footer-right',
				'footer-disclaimer'
			) );
	}

	/**
	 * Set up the metaboxes
	 * @since  1.5.3
	 */
	function add_footer_settings_metabox() {

		// hook in our save notices
		add_action( "cmb2_save_options-page_fields_{$this->metabox_id}", array( $this, 'settings_notices' ), 10, 2 );

		$cmb = new_cmb2_box( array(
			'id'         => $this->metabox_id,
			'hookup'     => false,
			'cmb_styles' => true,
			'show_on'    => array(
				// These are important, don't remove
				'key'   => 'options-page',
				'value' => array( $this->key, )
			),
		) );

		// Set our Footer fields

		$cmb->add_field( array(
			'name' => __( 'Disclaimer', 'equity' ),
			'desc' => __( 'Text or shortcodes to display in Footer Disclaimer text area', 'equity' ),
			'id'   => 'footer-disclaimer',
			'type' => 'wysiwyg',
			'default' => __( 'Optional Disclaimer - This can be edited under Equity > Footer in the Dashboard or deleted altogether. <div class="realty-logos">[properticon icon="properticons-logo-eho" size="67"][properticon icon="properticons-logo-realtor" size="70"]</div>', 'equity'),
			'options' => array(
				'textarea_rows' => 3,
				'tabindex' => 1,
				'media_buttons' => false,
				'teeny'         => true,
				),
		) );

		$cmb->add_field( array(
			'name' => __( 'Footer Left', 'equity' ),
			'desc' => __( 'Text or shortcodes to display in Footer Left text area', 'equity' ),
			'id'   => 'footer-left',
			'type' => 'wysiwyg',
			'default' => '[footer_copyright] &middot; [footer_equity_link url="https://idxbroker.com/" before=""]',
			'options' => array(
				'textarea_rows' => 3,
				'tabindex' => 2,
				'media_buttons' => false,
				'teeny'         => true,
				),
		) );

		$cmb->add_field( array(
			'name' => __( 'Footer Right', 'equity' ),
			'desc' => __( 'Text or shortcodes to display in Footer Right text area', 'equity' ),
			'id'   => 'footer-right',
			'type' => 'wysiwyg',
			'default' => '[footer_loginout]',
			'options' => array(
				'textarea_rows' => 3,
				'tabindex' => 3,
				'media_buttons' => false,
				'teeny'         => true,
				),
		) );

	}

	/**
	 * Register settings notices for display
	 *
	 * @since  1.5.3
	 * @param  int   $object_id Option key
	 * @param  array $updated   Array of updated fields
	 * @return void
	 */
	public function settings_notices( $object_id, $updated ) {
		if ( $object_id !== $this->key || empty( $updated ) ) {
			return;
		}

		add_settings_error( $this->key . '-notices', '', __( 'Footer settings updated.', 'equity' ), 'updated' );
		settings_errors( $this->key . '-notices' );
	}

	/**
	 * Public getter method for retrieving protected/private variables
	 * @since  1.5.3
	 * @param  string  $field Field to retrieve
	 * @return mixed          Field value or exception is thrown
	 */
	public function __get( $field ) {
		// Allowed fields to retrieve
		if ( in_array( $field, array( 'key', 'metabox_id', 'title', 'options_page' ), true ) ) {
			return $this->{$field};
		}

		throw new Exception( 'Invalid property: ' . $field );
	}

}

/**
 * Helper function to get/return the EQUITY_Footer_Settings object
 * @since  1.5.3
 * @return EQUITY_Footer_Settings object
 */
function equity_add_footer_settings() {
	static $object = null;
	if ( is_null( $object ) ) {
		$object = new EQUITY_Footer_Settings();
		$object->hooks();
	}

	return $object;
}

// Get it started
add_action( 'equity_admin_menu', 'equity_add_footer_settings' );