<?php
/**
 * Equity Framework
 *
 * WARNING: This file is part of the core Equity Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Equity\Admin
 * @author  IDX, LLC
 * @license GPL-2.0+
 * @link    
 */


add_action( 'admin_menu', 'equity_add_inpost_scripts_box' );
/**
 * Register a new meta box to the post or page edit screen, so that the user can apply scripts on a per-post or
 * per-page basis.
 *
 * The scripts field was previously part of the SEO meta box, and was therefore hidden when an SEO plugin was active.
 *
 * @since 1.0
 *
 * @see equity_inpost_scripts_box() Generates the content in the meta box.
 */
function equity_add_inpost_scripts_box() {

	//* If user doesn't have unfiltered html capability, don't show this box
	if ( ! current_user_can( 'unfiltered_html' ) )
		return;

	foreach ( (array) get_post_types( array( 'public' => true ) ) as $type ) {
		if ( post_type_supports( $type, 'equity-scripts' ) )
			add_meta_box( 'equity_inpost_scripts_box', __( 'Scripts', 'equity' ), 'equity_inpost_scripts_box', $type, 'normal', 'low' );
	}

}

/**
 * Callback for in-post Scripts meta box.
 *
 * @since 1.0
 *
 * @uses equity_get_custom_field() Get custom field value.
 */
function equity_inpost_scripts_box() {

	wp_nonce_field( 'equity_inpost_scripts_save', 'equity_inpost_scripts_nonce' );
	?>

	<p><label for="equity_scripts" class="screen-reader-text"><b><?php _e( 'Page-specific Scripts', 'equity' ); ?></b></label></p>
	<p><textarea class="widefat" rows="4" cols="4" name="equity_scripts[_equity_scripts]" id="equity_scripts"><?php echo esc_textarea( equity_get_custom_field( '_equity_scripts' ) ); ?></textarea></p>
	<p><?php printf( __( 'Suitable for custom tracking, conversion or other page-specific script. Must include %s tags.', 'equity' ), equity_code( 'script' ) ); ?></p>
	<?php

}

add_action( 'save_post', 'equity_inpost_scripts_save', 1, 2 );
/**
 * Save the Scripts settings when we save a post or page.
 *
 * @since 1.0
 *
 * @uses equity_save_custom_fields() Perform checks and saves post meta / custom field data to a post or page.
 *
 * @param integer  $post_id Post ID.
 * @param stdClass $post    Post object.
 *
 * @return null Returns null if no value POSTed.
 */
function equity_inpost_scripts_save( $post_id, $post ) {

	if ( ! isset( $_POST['equity_scripts'] ) )
		return;

	 //* If user doesn't have unfiltered html capability, don't try to save
	if ( ! current_user_can( 'unfiltered_html' ) )
		return;

	//* Merge user submitted options with fallback defaults
	$data = wp_parse_args( $_POST['equity_scripts'], array(
		'_equity_scripts' => '',
	) );

	equity_save_custom_fields( $data, 'equity_inpost_scripts_save', 'equity_inpost_scripts_nonce', $post );

}

add_action( 'admin_menu', 'equity_add_inpost_layout_box' );
/**
 * Register a new meta box to the post or page edit screen, so that the user can set layout options on a per-post or
 * per-page basis.
 *
 * @since 1.0
 *
 * @see equity_inpost_layout_box() Generates the content in the boxes
 *
 * @return null Returns null if Equity layouts are not supported
 */
function equity_add_inpost_layout_box() {

	if ( ! current_theme_supports( 'equity-inpost-layouts' ) )
		return;

	foreach ( (array) get_post_types( array( 'public' => true ) ) as $type ) {
		if ( post_type_supports( $type, 'equity-layouts' ) )
			add_meta_box( 'equity_inpost_layout_box', __( 'Layout Settings', 'equity' ), 'equity_inpost_layout_box', $type, 'normal', 'high' );
	}

}

/**
 * Callback for in-post layout meta box.
 *
 * @since 1.0
 *
 * @uses equity_get_custom_field() Get custom field value.
 * @uses equity_layout_selector()  Layout selector.
 */
function equity_inpost_layout_box() {

	wp_nonce_field( 'equity_inpost_layout_save', 'equity_inpost_layout_nonce' );

	$layout = equity_get_custom_field( '_equity_layout' );

	?>
	<div class="equity-layout-selector">
		<p><input type="radio" name="equity_layout[_equity_layout]" class="default-layout" id="default-layout" value="" <?php checked( $layout, '' ); ?> /> <label class="default" for="default-layout"><?php printf( __( 'Default Layout set in <a href="%s">Customize</a>', 'equity' ), esc_url( admin_url( 'customize.php' ) ) ); ?></label></p>

		<p><?php equity_layout_selector( array( 'name' => 'equity_layout[_equity_layout]', 'selected' => $layout, 'type' => 'site' ) ); ?></p>
	</div>

	<br class="clear" />

	<p><label for="equity_custom_body_class"><b><?php _e( 'Custom Body Class', 'equity' ); ?></b></label></p>
	<p><input class="large-text" type="text" name="equity_layout[_equity_custom_body_class]" id="equity_custom_body_class" value="<?php echo esc_attr( equity_get_custom_field( '_equity_custom_body_class' ) ); ?>" /></p>

	<p><label for="equity_custom_post_class"><b><?php _e( 'Custom Post Class', 'equity' ); ?></b></label></p>
	<p><input class="large-text" type="text" name="equity_layout[_equity_custom_post_class]" id="equity_custom_post_class" value="<?php echo esc_attr( equity_get_custom_field( '_equity_custom_post_class' ) ); ?>" /></p>
	<?php

}

add_action( 'save_post', 'equity_inpost_layout_save', 1, 2 );
/**
 * Save the layout options when we save a post or page.
 *
 * Since there's no sanitizing of data, the values are pulled from identically named keys in $_POST.
 *
 * @since 1.0
 *
 * @uses equity_save_custom_fields() Perform checks and saves post meta / custom field data to a post or page.
 *
 * @param integer  $post_id Post ID.
 * @param stdClass $post    Post object.
 *
 * @return mixed Returns post id if permissions incorrect, null if doing autosave, ajax or future post, false if update
 *               or delete failed, and true on success.
 *
 */
function equity_inpost_layout_save( $post_id, $post ) {

	if ( ! isset( $_POST['equity_layout'] ) )
		return;

	$data = wp_parse_args( $_POST['equity_layout'], array(
		'_equity_layout'            => '',
		'_equity_custom_body_class' => '',
		'_equity_post_class'        => '',
	) );

	$data = array_map( 'equity_sanitize_html_classes', $data );

	equity_save_custom_fields( $data, 'equity_inpost_layout_save', 'equity_inpost_layout_nonce', $post );

}

