<?php
/**
 * Equity Framework
 *
 * WARNING: This file is part of the core Equity Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Equity\Admin
 * @author  IDX, LLC
 * @license GPL-2.0+
 * @link    
 */

add_action( 'after_setup_theme', 'equity_add_admin_menu' );
/**
 * Add Equity top-level item in admin menu.
 *
 * Calls the `equity_admin_menu hook` at the end - all submenu items should be attached to that hook to ensure
 * correct ordering.
 *
 * @since 1.0
 *
 * @global \EQUITY_Admin_Settings _equity_admin_settings          Theme Settings page object.
 */
function equity_add_admin_menu() {

	if ( ! is_admin() )
		return;

	global $_equity_admin_settings;

	$_equity_admin_settings = new EQUITY_Admin_Settings;

	do_action( 'equity_admin_menu' );

}

add_action( 'equity_admin_menu', 'equity_add_admin_submenus' );
/**
 * Add submenu items under Equity item in admin menu.
 *
 * @since 1.0
 *
 * @see EQUITY_Admin_Readme Readme class
 *
 * @global string $_equity_admin_readme
 *
 * @return null Returns null if Equity menu is disabled
 */
function equity_add_admin_submenus() {

	//* Do nothing, if not viewing the admin
	if ( ! is_admin() )
		return;

	global $_equity_admin_readme;

	//* Don't add submenu items if Equity menu is disabled
	if( ! current_theme_supports( 'equity-admin-menu' ) )
		return;

}

add_action( 'admin_menu', 'equity_add_cpt_archive_page', 5 );
/**
 * Add archive settings page to relevant custom post type registrations.
 *
 * An instance of `EQUITY_Admin_CPT_Archive_Settings` is instantiated for each relevant CPT, assigned to an individual
 * global variable.
 *
 * @since 1.0
 *
 * @uses \EQUITY_Admin_CPT_Archive_Settings     CPT Archive Settings page class.
 * @uses equity_get_cpt_archive_types()         Get list of custom post types which need an archive settings page.
 * @uses equity_has_post_type_archive_support() Check post type has archive support.
 */
function equity_add_cpt_archive_page() {
	$post_types = equity_get_cpt_archive_types();

	foreach( $post_types as $post_type ) {
		if ( equity_has_post_type_archive_support( $post_type->name ) ) {
			$admin_object_name = '_equity_admin_cpt_archives_' . $post_type->name;
			global ${$admin_object_name};
			${$admin_object_name} = new EQUITY_Admin_CPT_Archive_Settings( $post_type );
		}
	}
}

add_action('wp_before_admin_bar_render', 'equity_add_documentation_link_to_admin_bar');
/**
 * Add link to Theme Setup Guide in Admin Bar if Theme URI is defined in style.css
 *
 * @since 1.0
 *
 * @uses wp_get_theme()
 */
function equity_add_documentation_link_to_admin_bar() {

	global $wp_admin_bar;

	$active_theme = wp_get_theme();
	$theme_uri = $active_theme->get( 'ThemeURI' );
	if ($theme_uri) {
		$wp_admin_bar->add_menu( array(
			'parent' => false,
			'id' => 'theme-setup-guide',
			'title' => __( 'Theme Setup Guide', 'equity' ),
			'href' => $theme_uri,
			'meta' => array('target' => '_blank')
		));
	}
}
