<?php
/**
 * Equity Framework
 *
 * WARNING: This file is part of the core Equity Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Equity\Admin
 * @author  IDX, LLC
 * @license GPL-2.0+
 * @link    
 */

/**
 * Registers a new admin page, providing content and corresponding menu item for the Theme Settings page.
 *
 * @package Equity\Admin
 *
 * @since 1.0
 */
class EQUITY_Admin_Settings extends EQUITY_Admin_Boxes {

	/**
	 * Create an admin menu item and settings page.
	 *
	 * @since 1.0
	 *
	 * @uses EQUITY_ADMIN_IMAGES_URL       URL for admin images.
	 * @uses EQUITY_SETTINGS_FIELD         Settings field key.
	 * @uses PARENT_THEME_VERSION          Equity Framework version.
	 * @uses \EQUITY_Admin::create()       Create an admin menu item and settings page.
	 */
	function __construct() {

		$page_id = 'equity';

		$menu_ops = apply_filters(
			'equity_theme_settings_menu_ops',
			array(
				'main_menu' => array(
					'sep' => array(
						'sep_position'   => '58.995',
						'sep_capability' => 'edit_theme_options',
					),
					'page_title' => 'Theme Settings',
					'menu_title' => 'Equity',
					'capability' => 'edit_theme_options',
					// 'icon_url'   => EQUITY_ADMIN_IMAGES_URL . '/equity-menu.png',
					'icon_url'   => 'dashicons-location',
					'position'   => '58.996',
				),
				'first_submenu' => array( //* Do not use without 'main_menu'
					'page_title' => __( 'Theme Settings', 'equity' ),
					'menu_title' => __( 'Theme Settings', 'equity' ),
					'capability' => 'edit_theme_options',
				),
			)
		);

		$page_ops = apply_filters(
			'equity_theme_settings_page_ops',
			array(
				'save_button_text'  => __( 'Save Settings', 'equity' ),
				'reset_button_text' => __( 'Reset Settings', 'equity' ),
				'saved_notice_text' => __( 'Settings saved.', 'equity' ),
				'reset_notice_text' => __( 'Settings reset.', 'equity' ),
				'error_notice_text' => __( 'Error saving settings.', 'equity' ),
			)
		);

		$settings_field = EQUITY_SETTINGS_FIELD;

		$default_settings = apply_filters(
			'equity_theme_settings_defaults',
			array(
				'feed_uri'                  => '',
				'redirect_feed'             => 0,
				'comments_feed_uri'         => '',
				'redirect_comments_feed'    => 0,
				'idx_feed_uri'              => '',
				'comments_pages'            => 0,
				'comments_posts'            => 1,
				'trackbacks_pages'          => 0,
				'trackbacks_posts'          => 1,
				// 'breadcrumb_home'           => 0,
				// 'breadcrumb_front_page'     => 0,
				// 'breadcrumb_posts_page'     => 0,
				// 'breadcrumb_single'         => 0,
				// 'breadcrumb_page'           => 0,
				// 'breadcrumb_archive'        => 0,
				// 'breadcrumb_404'            => 0,
				// 'breadcrumb_attachment'	   => 0,
				'site_layout'               => equity_get_default_layout(),
				'content_archive'           => 'full',
				'content_archive_thumbnail' => 0,
				'image_size'                => '',
				'image_alignment'           => 'alignleft',
				'posts_nav'                 => 'numeric',
				'blog_cat'                  => '',
				'blog_cat_exclude'          => '',
				'blog_cat_num'              => 10,
				'header_scripts'            => '',
				'footer_scripts'            => '',
				'theme_version'             => PARENT_THEME_VERSION,
				'equity_idx_domain'			=> '',
			)
		);

		$this->create( $page_id, $menu_ops, $page_ops, $settings_field, $default_settings );

		add_action( 'equity_settings_sanitizer_init', array( $this, 'sanitizer_filters' ) );

	}

	/**
	 * Register each of the settings with a sanitization filter type.
	 *
	 * @since 1.0
	 *
	 * @uses equity_add_option_filter() Assign filter to array of settings.
	 *
	 * @see \EQUITY_Settings_Sanitizer::add_filter() Add sanitization filters to options.
	 */
	public function sanitizer_filters() {

		equity_add_option_filter(
			'one_zero',
			$this->settings_field,
			array(
				// 'breadcrumb_front_page',
				// 'breadcrumb_home',
				// 'breadcrumb_single',
				// 'breadcrumb_page',
				// 'breadcrumb_posts_page',
				// 'breadcrumb_archive',
				// 'breadcrumb_404',
				// 'breadcrumb_attachment',
				'redirect_feed',
				'redirect_comments_feed',
				'comments_posts',
				'comments_pages',
				'content_archive_thumbnail',
				'trackbacks_posts',
				'trackbacks_pages',
			)
		);

		equity_add_option_filter(
			'no_html',
			$this->settings_field,
			array(
				'blog_cat_exclude',
				'blog_title',
				'content_archive',
				'posts_nav',
				'site_layout',
				'agent_address',
				'agent_phone',
				'agent_phone_country_code',
			)
		);

		equity_add_option_filter(
			'absint',
			$this->settings_field,
			array(
				'blog_cat',
				'blog_cat_num',
				'content_archive_limit',
			)
		);

		equity_add_option_filter(
			'requires_unfiltered_html',
			$this->settings_field,
			array(
				'header_scripts',
				'footer_scripts',
			)
		);

		equity_add_option_filter(
			'url',
			$this->settings_field,
			array(
				'feed_uri',
				'comments_feed_uri',
				'idx_feed_uri',
				'facebook_url',
				'twitter_url',
				'linkedin_url',
				'youtube_url',
				'pinterest_url',
				'instagram_url',
				'yelp_url',
				'google_url',
				'equity_idx_domain',
			)
		);

		equity_add_option_filter(
			'email_address',
			$this->settings_field,
			array(
				'agent_email',
			)
		);

	}

	/**
	 * Contextual help content.
	 *
	 * @since 1.0
	 */
	public function help() {

		$screen = get_current_screen();

		$theme_settings_help =
			'<h3>' . __( 'Theme Settings', 'equity' ) . '</h3>' .
			'<p>'  . __( 'Your Theme Settings provides control over how the theme works. You will be able to control a lot of common and even advanced features from this menu. Some child themes may add additional menu items to this list, including the ability to select different color schemes or set theme specific features such as a slider. Each of the boxes can be collapsed by clicking the box header and expanded by doing the same. They can also be dragged into any order you desire or even hidden by clicking on "Screen Options" in the top right of the screen and "unchecking" the boxes you do not want to see. Below you\'ll find the items common to every child theme...', 'equity' ) . '</p>';

		$idx_account_info_help =
			'<h3>' . __( 'IDX Account', 'equity' ) . '</h3>' .
			'<p>'  . __( 'Here you can enter the domain for your IDX account, in the case of using a developement environment or if the WordPress site URL does not match.', 'equity' ) . '</p>';

		$agent_info_help =
			'<h3>' . __( 'Agent Info', 'equity' ) . '</h3>' .
			'<p>'  . __( 'Here you can enter your social media and contact info to be displayed using the theme\'s shortcodes.', 'equity' ) . '</p>';

		$feeds_help =
			'<h3>' . __( 'Custom Feeds', 'equity' ) . '</h3>' .
			'<p>'  . __( 'If you use Feedburner to handle your rss feed(s) you can use this function to set your site\'s native feed to redirect to your Feedburner feed.', 'equity' ) . '</p>' .
			'<p>'  . __( 'By filling in the feed links calling for the main site feed, it will display as a link to Feedburner.', 'equity' ) . '</p>' .
			'<p>'  . __( 'By checking the "Redirect Feed" box, all traffic to default feed links will be redirected to the Feedburner link instead.', 'equity' ) . '</p>' .
			'<p>'  . __( 'If using IDX Broker, you can enter the URL for your XML sitemap and a link will be output to the document <head>.', 'equity' ) . '</p>';

		$layout_help =
			'<h3>' . __( 'Default Layout', 'equity' ) . '</h3>' .
			'<p>'  . __( 'This lets you select the default layout for your entire site. On most of the child themes you\'ll see these options:', 'equity' ) . '</p>' .
			'<ul>' .
				'<li>' . __( 'Content Sidebar', 'equity' ) . '</li>' .
				'<li>' . __( 'Sidebar Content', 'equity' ) . '</li>' .
				'<li>' . __( 'Full Width Content', 'equity' ) . '</li>' .
			'</ul>' .
			'<p>'  . __( 'These options can be extended or limited by the child theme. Additionally, many of the child themes do not allow different layouts on the home page as they have been designed for a specific home page layout.', 'equity' ) . '</p>' .
			'<p>'  . __( 'This layout can also be overridden in the post/page/term layout options on each post/page/term.', 'equity' ) . '</p>';

		$header_help =
			'<h3>' . __( 'Header', 'equity') . '</h3>' .
			'<p>'  . __( 'The <strong>Dynamic text</strong> option will use the Site Title and Site Description from your site\'s settings in your header.', 'equity' ) . '</p>' .
			'<p>'  . __( 'The <strong>Image logo</strong> option will use a logo image file in the header instead of the site\'s title and description. This setting adds a .header-image class to your site, allowing you to specify the header image in your child theme\'s style.css. By default, the logo can be saved as logo.png and saved to the images folder of your child theme.', 'equity' ) . '</p>';

		// $breadcrumbs_help =
		// 	'<h3>' . __( 'Breadcrumbs', 'equity' ) . '</h3>' .
		// 	'<p>'  . __( 'This box lets you define where the "Breadcrumbs" display. The Breadcrumb is the navigation tool that displays where a visitor is on the site at any given moment.', 'equity' ) . '</p>';

		$comments_help =
			'<h3>' . __( 'Comments and Trackbacks', 'equity' ) . '</h3>' .
			'<p>'  . __( 'This allows a site wide decision on whether comments and trackbacks (notifications when someone links to your page) are enabled for posts and pages.', 'equity' ) . '</p>' .
			'<p>'  . __( 'If you enable comments or trackbacks here, it can be disabled on an individual post or page. If you disable here, they cannot be enabled on an individual post or page.', 'equity' ) . '</p>';

		$archives_help =
			'<h3>' . __( 'Content Archives', 'equity' ) . '</h3>' .
			'<p>'  . __( 'In the Equity Theme Settings you may change the site wide Content Archives options to control what displays in the site\'s Archives.', 'equity' ) . '</p>' .
			'<p>'  . __( 'Archives include any pages using the blog template, category pages, tag pages, date archive, author archives, and the latest posts if there is no custom home page.', 'equity' ) . '</p>' .
			'<p>'  . __( 'The first option allows you to display the post content or the post excerpt. The Display post content setting will display the entire post including HTML code up to the <!--more--> tag if used (this is HTML for the comment tag that is not displayed in the browser).', 'equity' ) . '</p>' .
			'<p>'  . __( 'It may also be coupled with the second field "Limit content to [___] characters" to limit the content to a specific number of letters or spaces. This will strip any HTML, but allows for more precise and easily changed lengths than the excerpt.', 'equity' ) . '</p>' .
			'<p>'  . __( 'The Display post excerpt setting will display the first 55 words of the post after also stripping any included HTML or the manual/custom excerpt added in the post edit screen.', 'equity' ) . '</p>' .
			'<p>'  . __( 'The \'Include post image?\' setting allows you to show a thumbnail of the first attached image or currently set featured image.', 'equity' ) . '</p>' .
			'<p>'  . __( 'This option should not be used with the post content unless the content is limited to avoid duplicate images.', 'equity' ) . '</p>' .
			'<p>'  . __( 'The \'Image Size\' list is populated by the available image sizes defined in the theme.', 'equity' ) . '</p>' .
			'<p>'  . __( 'Post Navigation Technique allows you to select one of three navigation methods.', 'equity' ) . '</p>';

		$blog_help =
			'<h3>' . __( 'Blog Page', 'equity' ) . '</h3>' .
			'<p>'  . __( 'This works with the Blog Template, which is a page template that shows your latest posts. It\'s what people see when they land on your homepage.', 'equity' ) . '</p>' .
			'<p>'  . __( 'In the General Settings you can select a specific category to display from the drop down menu, and exclude categories by ID, or even select how many posts you\'d like to display on this page.', 'equity' ) . '</p>' .
			'<p>'  . __( 'There are some special features of the Blog Template that allow you to specify which category to show on each page using the template, which is helpful if you have a "News" category (or something else) that you want to display separately.', 'equity' ) . '</p>';

		$scripts_help =
			'<h3>' . __( 'Header and Footer Scripts', 'equity' ) . '</h3>' .
			'<p>'  . __( 'This provides you with two fields that will output to the <head></head> of your site and just before the </body>. These will appear on every page of the site and are a great way to add analytic code and other scripts. You cannot use PHP in these fields. If you need to use PHP then you should look into the Equity Simple Hooks plugin.', 'equity' ) . '</p>';

		$screen->add_help_tab( array(
			'id'      => $this->pagehook . '-theme-settings',
			'title'   => __( 'Theme Settings', 'equity' ),
			'content' => $theme_settings_help,
		) );
		$screen->add_help_tab( array(
			'id'      => $this->pagehook . '-idx-account-info',
			'title'   => __( 'IDX Account Info', 'equity' ),
			'content' => $idx_account_info_help,
		) );
		$screen->add_help_tab( array(
			'id'      => $this->pagehook . '-agent-info',
			'title'   => __( 'Agent Info', 'equity' ),
			'content' => $agent_info_help,
		) );
		$screen->add_help_tab( array(
			'id'      => $this->pagehook . '-feeds',
			'title'   => __( 'Custom Feeds', 'equity' ),
			'content' => $feeds_help,
		) );
		$screen->add_help_tab( array(
			'id'      => $this->pagehook . '-layout',
			'title'   => __( 'Default Layout', 'equity' ),
			'content' => $layout_help,
		) );
		$screen->add_help_tab( array(
			'id'      => $this->pagehook . '-comments',
			'title'   => __( 'Comments and Trackbacks', 'equity' ),
			'content' => $comments_help,
		) );
		$screen->add_help_tab( array(
			'id'      => $this->pagehook . '-archives',
			'title'   => __( 'Content Archives', 'equity' ),
			'content' => $archives_help,
		) );
		// $screen->add_help_tab( array(
		// 	'id'      => $this->pagehook . '-breadcrumbs',
		// 	'title'   => __( 'Breadcrumbs', 'equity' ),
		// 	'content' => $breadcrumbs_help,
		// ) );
		$screen->add_help_tab( array(
			'id'      => $this->pagehook . '-blog',
			'title'   => __( 'Blog Page', 'equity' ),
			'content' => $blog_help,
		) );
		$screen->add_help_tab( array(
			'id'      => $this->pagehook . '-scripts',
			'title'   => __( 'Header and Footer Scripts', 'equity' ),
			'content' => $scripts_help,
		) );

	}

	/**
 	 * Register meta boxes on the Theme Settings page.
 	 *
 	 * Some of the meta box additions are dependent on certain theme support or user capabilities.
 	 *
 	 * The 'equity_theme_settings_metaboxes' action hook is called at the end of this function.
 	 *
 	 * @since 1.0
 	 *
 	 * @see \EQUITY_Admin_Settings::feeds_box()         Callback for Custom Feeds box.
 	 * @see \EQUITY_Admin_Settings::comments_box()      Callback for Comments and Trackbacks box.
 	 * @see \EQUITY_Admin_Settings::post_archives_box() Callback for Content Archives box.
 	 * @see \EQUITY_Admin_Settings::breadcrumb_box()    Callback for Breadcrumbs box.
 	 * @see \EQUITY_Admin_Settings::blogpage_box()      Callback for Blog Page box.
 	 * @see \EQUITY_Admin_Settings::scripts_box()       Callback for Header and Footer Scripts box (if user has
 	 *                                                   unfiltered_html capability).
 	 */
	function metaboxes() {

		add_meta_box( 'equity-theme-settings-version', __( 'Information', 'equity' ), array( $this, 'info_box' ), $this->pagehook, 'main', 'high' );
		
		if( class_exists( 'Idx_Broker_Plugin' ) )
			add_meta_box( 'equity-theme-settings-idx-account-info', __( 'IDX Info', 'equity' ), array( $this, 'idx_account_info_box' ), $this->pagehook, 'main' );

		add_meta_box( 'equity-theme-settings-agent-info', __( 'Agent Info', 'equity' ), array( $this, 'agent_info_box' ), $this->pagehook, 'main' );

		add_meta_box( 'equity-theme-settings-feeds', __( 'Custom Feeds', 'equity' ), array( $this, 'feeds_box' ), $this->pagehook, 'main' );

		add_meta_box( 'equity-theme-settings-layout', __( 'Default Layout', 'equity' ), array( $this, 'layout_box' ), $this->pagehook, 'main' );

		// if ( current_theme_supports( 'equity-breadcrumbs' ) )
		// 	add_meta_box( 'equity-theme-settings-breadcrumb', __( 'Breadcrumbs', 'equity' ), array( $this, 'breadcrumb_box' ), $this->pagehook, 'main' );
		add_meta_box( 'equity-theme-settings-comments', __( 'Comments and Trackbacks', 'equity' ), array( $this, 'comments_box' ), $this->pagehook, 'main' );
		
		add_meta_box( 'equity-theme-settings-posts', __( 'Content Archives', 'equity' ), array( $this, 'post_archives_box' ), $this->pagehook, 'main' );
		
		add_meta_box( 'equity-theme-settings-blogpage', __( 'Blog Page Template', 'equity' ), array( $this, 'blogpage_box' ), $this->pagehook, 'main' );

		if ( current_user_can( 'unfiltered_html' ) )
			add_meta_box( 'equity-theme-settings-scripts', __( 'Header and Footer Scripts', 'equity' ), array( $this, 'scripts_box' ), $this->pagehook, 'main' );

		do_action( 'equity_theme_settings_metaboxes', $this->pagehook );

	}

	/**
	 * Callback for Theme Settings Information meta box.
	 *
	 * If equity-auto-updates is not supported, some of the fields will not display.
	 *
	 * @since 1.0
	 *
	 * @uses PARENT_THEME_RELEASE_DATE      Date of current release of Equity Framework.
	 * @uses \EQUITY_Admin::get_field_id()    Construct field ID.
	 * @uses \EQUITY_Admin::get_field_name()  Construct field name.
	 * @uses \EQUITY_Admin::get_field_value() Retrieve value of key under $this->settings_field.
	 *
	 * @see \EQUITY_Admin_Settings::metaboxes() Register meta boxes on the Theme Settings page.
	 */
	function info_box() {

		?>
		<p><strong><?php _e( 'Equity Framework Version:', 'equity' ); ?></strong> <?php echo PARENT_THEME_VERSION; ?> &#x000B7; <strong><?php _e( 'Released:', 'equity' ); ?></strong> <?php echo PARENT_THEME_RELEASE_DATE; ?></p>
		
		<?php
		$active_theme = wp_get_theme();
		$theme_uri = $active_theme->get( 'ThemeURI' );
		$theme_name = $active_theme->get( 'Name' );
		
		if ( is_child_theme() ) { ?>
			<p><strong><?php _e( 'Child Theme Information', 'equity' ); ?></strong><br />
			<strong><?php _e('Name: ', 'equity'); ?></strong><?php echo CHILD_THEME_NAME; ?><br />
			<strong><?php _e('Version: ', 'equity'); ?></strong><?php echo CHILD_THEME_VERSION; ?><br />
			<?php printf( '<a href="%s">%s %s %s</a></p>', $theme_uri, __( 'View ', 'equity' ), $theme_name, __( 'Theme Setup Guide', 'equity' ) ); ?>
		<?php
		}
	}

	/**
	 * Callback for Theme Settings IDX info meta box.
	 *
	 * @since 1.0
	 *
	 * @uses \EQUITY_Admin::get_field_id()    Construct field ID.
	 * @uses \EQUITY_Admin::get_field_name()  Construct field name.
	 * @uses \EQUITY_Admin::get_field_value() Retrieve value of key under $this->settings_field.
	 *
	 * @see \EQUITY_Admin_Settings::metaboxes() Register meta boxes on the Theme Settings page.
	 */
	function idx_account_info_box() {
		?>
		<p>
			<label for="<?php $this->field_id( 'equity_idx_domain' ); ?>"><?php _e( 'Your WordPress site URL will be used by default. If using a development environment or if your WordPress URL does not match your IDX account info, enter the URL in your IDX account here:', 'equity' ); ?></label><br />
			<input type="text" name="<?php $this->field_name( 'equity_idx_domain' ); ?>" class="regular-text" id="<?php $this->field_id( 'equity_idx_domain' ); ?>" value="<?php echo esc_attr( $this->get_field_value( 'equity_idx_domain' ) ); ?>" />
		</p>
		<?php
	}

	/**
	 * Callback for Theme Settings Agent Info meta box.
	 *
	 * @since 1.0
	 *
	 * @uses \EQUITY_Admin::get_field_id()    Construct field ID.
	 * @uses \EQUITY_Admin::get_field_name()  Construct field name.
	 * @uses \EQUITY_Admin::get_field_value() Retrieve value of key under $this->settings_field.
	 *
	 * @see \EQUITY_Admin_Settings::metaboxes() Register meta boxes on the Theme Settings page.
	 */
	function agent_info_box() {
		?>
		<p>Facebook URL:<br />
			<input type="text" name="<?php $this->field_name( 'facebook_url' ); ?>" value="<?php echo esc_attr( $this->get_field_value( 'facebook_url') ); ?>" size="50" />
		</p>

		<p>Twitter URL:<br />
			<input type="text" name="<?php $this->field_name( 'twitter_url' ); ?>" value="<?php echo esc_attr( $this->get_field_value( 'twitter_url') ); ?>" size="50" />
		</p>

		<p>LinkedIn URL:<br />
			<input type="text" name="<?php $this->field_name( 'linkedin_url' ); ?>" value="<?php echo esc_attr( $this->get_field_value( 'linkedin_url') ); ?>" size="50" />
		</p>

		<p>YouTube URL:<br />
			<input type="text" name="<?php $this->field_name( 'youtube_url' ); ?>" value="<?php echo esc_attr( $this->get_field_value( 'youtube_url') ); ?>" size="50" />
		</p>

		<p>Pinterest URL:<br />
			<input type="text" name="<?php $this->field_name( 'pinterest_url' ); ?>" value="<?php echo esc_attr( $this->get_field_value( 'pinterest_url') ); ?>" size="50" />
		</p>

		<p>Instagram URL:<br />
			<input type="text" name="<?php $this->field_name( 'instagram_url' ); ?>" value="<?php echo esc_attr( $this->get_field_value( 'instagram_url') ); ?>" size="50" />
		</p>

		<p>Yelp URL:<br />
			<input type="text" name="<?php $this->field_name( 'yelp_url' ); ?>" value="<?php echo esc_attr( $this->get_field_value( 'yelp_url') ); ?>" size="50" />
		</p>

		<p>Google My Business URL:<br />
			<input type="text" name="<?php $this->field_name( 'google_url' ); ?>" value="<?php echo esc_attr( $this->get_field_value( 'google_url') ); ?>" size="50" />
		</p>

		<p> <?php _e( 'Address:', 'equity' ); ?><br />
			<input type="text" name="<?php $this->field_name( 'agent_address' ); ?>" value="<?php echo esc_attr( $this->get_field_value( 'agent_address') ); ?>" size="50" />
		</p>

		<p><?php _e( 'Phone:', 'equity' ); ?><br />
			<label for="<?php $this->field_name( 'agent_phone_country_code' ); ?>"><?php _e( 'Country Code', 'equity' ); ?></label>
			<input type="text" id="<?php $this->field_name( 'agent_phone_country_code' ); ?>" name="<?php $this->field_name( 'agent_phone_country_code' ); ?>" value="<?php echo esc_attr( $this->get_field_value( 'agent_phone_country_code') ); ?>" size="2" placeholder="<?php _e( 'Country Code', 'equity' ); ?>" />
			<label for="<?php $this->field_name( 'agent_phone' ); ?>"><?php _e( 'Phone Number with Area Code', 'equity' ); ?></label>
			<input type="text" id="<?php $this->field_name( 'agent_phone' ); ?>" name="<?php $this->field_name( 'agent_phone' ); ?>" value="<?php echo esc_attr( $this->get_field_value( 'agent_phone') ); ?>" size="20" placeholder="<?php _e( 'Phone Number with Area Code' , 'equity' ) ;?>" /><br />
			<small><strong><?php _e( 'For US Country code, use "1".', 'equity' ); ?></strong></small>
		</p>

		<?php echo '<p>' . __( 'Email:', 'equity' ) . '<br />'; ?>
			<input type="text" name="<?php $this->field_name( 'agent_email' ); ?>" value="<?php echo esc_attr( $this->get_field_value( 'agent_email') ); ?>" size="50" />
		</p>

		<?php
	}
	
	/**
	 * Callback for Theme Settings Custom Feeds meta box.
	 *
	 * @since 1.0
	 *
	 * @uses \EQUITY_Admin::get_field_id()    Construct field ID.
	 * @uses \EQUITY_Admin::get_field_name()  Construct field name.
	 * @uses \EQUITY_Admin::get_field_value() Retrieve value of key under $this->settings_field.
	 *
	 * @see \EQUITY_Admin_Settings::metaboxes() Register meta boxes on the Theme Settings page.
	 */
	function feeds_box() {

		?>
		<p>
			<label for="<?php $this->field_id( 'feed_uri' ); ?>"><?php _e( 'Enter your custom feed URL:', 'equity' ); ?></label><br />
			<input type="text" name="<?php $this->field_name( 'feed_uri' ); ?>" class="regular-text" id="<?php $this->field_id( 'feed_uri' ); ?>" value="<?php echo esc_attr( $this->get_field_value( 'feed_uri' ) ); ?>" />

			<label for="<?php $this->field_id( 'redirect_feed' ); ?>"><input type="checkbox" name="<?php $this->field_name( 'redirect_feed' ); ?>" id="<?php $this->field_id( 'redirect_feed' ); ?>" value="1"<?php checked( $this->get_field_value( 'redirect_feed' ) ); ?> />
			<?php _e( 'Redirect Feed?', 'equity' ); ?></label>
		</p>

		<p>
			<label for="<?php $this->field_id( 'comments_feed_uri' ); ?>"><?php _e( 'Enter your custom comments feed URL:', 'equity' ); ?></label><br />
			<input type="text" name="<?php $this->field_name( 'comments_feed_uri' ); ?>" class="regular-text" id="<?php $this->field_id( 'comments_feed_uri' ); ?>" value="<?php echo esc_attr( $this->get_field_value( 'comments_feed_uri' ) ); ?>" />

			<label for="<?php $this->field_id( 'redirect_comments_feed' ); ?>"><input type="checkbox" name="<?php $this->field_name( 'redirect_comments_feed' ); ?>" id="<?php $this->field_id( 'redirect_comments_feed' ); ?>" value="1"<?php checked( $this->get_field_value( 'redirect_comments__feed' ) ); ?> />
			<?php _e( 'Redirect Feed?', 'equity' ); ?></label>
		</p>

		<p><span class="description"><?php printf( __( 'If your custom feed(s) are not handled by Feedblitz or Feedburner, do not use the redirect options.', 'equity' ) ); ?></span></p>
		
	<?php
	}

	/**
	 * Callback for Theme Settings Default Layout meta box.
	 *
	 * @since 1.3
	 *
	 * @uses equity_layout_selector()         Outputs form elements for layout selector.
	 * @uses \Equity_Admin::get_field_name()  Construct field name.
	 * @uses \Equity_Admin::get_field_value() Retrieve value of key under $this->settings_field.
	 *
	 * @see \Equity_Admin_Settings::metaboxes() Register meta boxes on the Theme Settings page.
	 */
	function layout_box() {

		?>
		<p class="equity-layout-selector">
		<?php
		equity_layout_selector( array( 'name' => $this->get_field_name( 'site_layout' ), 'selected' => $this->get_field_value( 'site_layout' ), 'type' => 'site' ) );
		?>
		</p>

		<br class="clear" />
		<?php

	}

	/**
	 * Callback for Theme Settings Comments meta box.
	 *
	 * @since 1.3
	 *
	 * @uses \Equity_Admin::get_field_id()    Construct field ID.
	 * @uses \Equity_Admin::get_field_name()  Construct field name.
	 * @uses \Equity_Admin::get_field_value() Retrieve value of key under $this->settings_field.
	 *
	 * @see \Equity_Admin_Settings::metaboxes() Register meta boxes on the Theme Settings page.
	 */
	function comments_box() {

		?>
		<p>
			<?php _e( 'Enable Comments', 'equity' ); ?>
			<label for="<?php $this->field_id( 'comments_posts' ); ?>" title="Enable comments on posts"><input type="checkbox" name="<?php $this->field_name( 'comments_posts' ); ?>" id="<?php $this->field_id( 'comments_posts' ); ?>" value="1"<?php checked( $this->get_field_value( 'comments_posts' ) ); ?> />
			<?php _e( 'on posts?', 'equity' ); ?></label>

			<label for="<?php $this->field_id( 'comments_pages' ); ?>" title="Enable comments on pages"><input type="checkbox" name="<?php $this->field_name( 'comments_pages' ); ?>" id="<?php $this->field_id( 'comments_pages' ); ?>" value="1"<?php checked( $this->get_field_value( 'comments_pages' ) ); ?> />
			<?php _e( 'on pages?', 'equity' ); ?></label>
		</p>

		<p>
			<?php _e( 'Enable Trackbacks', 'equity' ); ?>
			<label for="<?php $this->field_id( 'trackbacks_posts' ); ?>" title="Enable trackbacks on posts"><input type="checkbox" name="<?php $this->field_name( 'trackbacks_posts' ); ?>" id="<?php $this->field_id( 'trackbacks_posts' ); ?>" value="1"<?php checked( $this->get_field_value( 'trackbacks_posts' ) ); ?> />
			<?php _e( 'on posts?', 'equity' ); ?></label>

			<label for="<?php $this->field_id( 'trackbacks_pages' ); ?>" title="Enable trackbacks on pages"><input type="checkbox" name="<?php $this->field_name( 'trackbacks_pages' ); ?>" id="<?php $this->field_id( 'trackbacks_pages' ); ?>" value="1"<?php checked( $this->get_field_value( 'trackbacks_pages' ) ); ?> />
			<?php _e( 'on pages?', 'equity' ); ?></label>
		</p>

		<p><span class="description"><?php _e( 'Comments and Trackbacks can also be disabled on a per post/page basis when creating/editing posts/pages.', 'equity' ); ?></span></p>
		<?php

	}

	/**
	 * Callback for Theme Settings Post Archives meta box.
	 *
	 * @since 1.3
	 *
	 * @uses equity_get_images_sizes()        Retrieve list of registered image sizes.
	 * @uses \Equity_Admin::get_field_id()    Construct field ID.
	 * @uses \Equity_Admin::get_field_name()  Construct field name.
	 * @uses \Equity_Admin::get_field_value() Retrieve value of key under $this->settings_field.
	 *
	 * @see \Equity_Admin_Settings::metaboxes() Register meta boxes on the Theme Settings page.
	 */
	function post_archives_box() {

		?>
		<p>
			<label for="<?php $this->field_id( 'content_archive' ); ?>"><?php _e( 'Select one of the following:', 'equity' ); ?></label>
			<select name="<?php $this->field_name( 'content_archive' ); ?>" id="<?php $this->field_id( 'content_archive' ); ?>">
			<?php
			$archive_display = apply_filters(
				'equity_archive_display_options',
				array(
					'full'     => __( 'Display post content', 'equity' ),
					'excerpts' => __( 'Display post excerpts', 'equity' ),
				)
			);
			foreach ( (array) $archive_display as $value => $name )
				echo '<option value="' . esc_attr( $value ) . '"' . selected( $this->get_field_value( 'content_archive' ), esc_attr( $value ), false ) . '>' . esc_html( $name ) . '</option>' . "\n";
			?>
			</select>
		</p>

		<div id="equity_content_limit_setting">
			<p>
				<label for="<?php $this->field_id( 'content_archive_limit' ); ?>"><?php _e( 'Limit content to', 'equity' ); ?>
				<input type="text" name="<?php $this->field_name( 'content_archive_limit' ); ?>" class="small-text" id="<?php $this->field_id( 'content_archive_limit' ); ?>" value="<?php echo esc_attr( $this->get_field_value( 'content_archive_limit' ) ); ?>" />
				<?php _e( 'characters', 'equity' ); ?></label>
			</p>

			<p><span class="description"><?php _e( 'Using this option will limit the text and strip all formatting from the text displayed. To use this option, choose "Display post content" in the select box above.', 'equity' ); ?></span></p>
		</div>

		<p>
			<label for="<?php $this->field_id( 'content_archive_thumbnail' ); ?>"><input type="checkbox" name="<?php $this->field_name( 'content_archive_thumbnail' ); ?>" id="<?php $this->field_id( 'content_archive_thumbnail' ); ?>" value="1"<?php checked( $this->get_field_value( 'content_archive_thumbnail' ) ); ?> />
			<?php _e( 'Include the Featured Image?', 'equity' ); ?></label>
		</p>

		<div id="equity_image_extras">
			<p>
				<label for="<?php $this->field_id( 'image_size' ); ?>"><?php _e( 'Image Size:', 'equity' ); ?></label>
				<select name="<?php $this->field_name( 'image_size' ); ?>" id="<?php $this->field_id( 'image_size' ); ?>">
				<?php
				$sizes = equity_get_image_sizes();
				foreach ( (array) $sizes as $name => $size )
					echo '<option value="' . esc_attr( $name ) . '"' . selected( $this->get_field_value( 'image_size' ), $name, FALSE ) . '>' . esc_html( $name ) . ' (' . absint( $size['width'] ) . ' &#x000D7; ' . absint( $size['height'] ) . ')</option>' . "\n";
				?>
				</select>
			</p>

			<p>
				<label for="<?php $this->field_id( 'image_alignment' ); ?>"><?php _e( 'Image Alignment:', 'equity' ); ?></label>
				<select name="<?php $this->field_name( 'image_alignment' ); ?>" id="<?php $this->field_id( 'image_alignment' ); ?>">
					<option value=""><?php _e( '- None -', 'equity' ) ?></option>
					<option value="alignleft" <?php selected( $this->get_field_value( 'image_alignment' ), 'alignleft' ); ?>><?php _e( 'Left', 'equity' ) ?></option>
					<option value="alignright" <?php selected( $this->get_field_value( 'image_alignment' ), 'alignright' ); ?>><?php _e( 'Right', 'equity' ) ?></option>
				</select>
			</p>
		</div>

		<p>
			<label for="<?php $this->field_id( 'posts_nav' ); ?>"><?php _e( 'Select Post Navigation Technique:', 'equity' ); ?></label>
			<select name="<?php $this->field_name( 'posts_nav' ); ?>" id="<?php $this->field_id( 'posts_nav' ); ?>">
				<option value="prev-next"<?php selected( 'prev-next', $this->get_field_value( 'posts_nav' ) ); ?>><?php _e( 'Previous / Next', 'equity' ); ?></option>
				<option value="numeric"<?php selected( 'numeric', $this->get_field_value( 'posts_nav' ) ); ?>><?php _e( 'Numeric', 'equity' ); ?></option>
			</select>
		</p>

		<p><span class="description"><?php _e( 'These options will affect any blog listings page, including archive, author, blog, category, search, and tag pages.', 'equity' ); ?></span></p>
		<?php

	}

	/**
	 * Callback for Theme Settings Breadcrumbs meta box.
	 *
	 * @since 1.0
	 *
	 * @uses \EQUITY_Admin::get_field_id()    Construct field ID.
	 * @uses \EQUITY_Admin::get_field_name()  Construct field name.
	 * @uses \EQUITY_Admin::get_field_value() Retrieve value of key under $this->settings_field.
	 *
	 * @see \EQUITY_Admin_Settings::metaboxes() Register meta boxes on the Theme Settings page.
	 */
	function breadcrumb_box() {

		?>
		<h4><?php _e( 'Enable on:', 'equity' ); ?></h4>
		<p>
			<?php if ( 'page' === get_option( 'show_on_front' ) ) : ?>
				<label for="<?php $this->field_id( 'breadcrumb_front_page' ); ?>"><input type="checkbox" name="<?php $this->field_name( 'breadcrumb_front_page' ); ?>" id="<?php $this->field_id( 'breadcrumb_front_page' ); ?>" value="1"<?php checked( $this->get_field_value( 'breadcrumb_front_page' ) ); ?> />
				<?php _e( 'Front Page', 'equity' ); ?></label>

				<label for="<?php $this->field_id( 'breadcrumb_posts_page' ); ?>"><input type="checkbox" name="<?php $this->field_name( 'breadcrumb_posts_page' ); ?>" id="<?php $this->field_id( 'breadcrumb_posts_page' ); ?>" value="1"<?php checked( $this->get_field_value( 'breadcrumb_posts_page' ) ); ?> />
				<?php _e( 'Posts Page', 'equity' ); ?></label>
			<?php else : ?>
				<label for="<?php $this->field_id( 'breadcrumb_home' ); ?>"><input type="checkbox" name="<?php $this->field_name( 'breadcrumb_home' ); ?>" id="<?php $this->field_id( 'breadcrumb_home' ); ?>" value="1"<?php checked( $this->get_field_value( 'breadcrumb_home' ) ); ?> />
				<?php _e( 'Homepage', 'equity' ); ?></label>
			<?php endif; ?>

			<label for="<?php $this->field_id( 'breadcrumb_single' ); ?>"><input type="checkbox" name="<?php $this->field_name( 'breadcrumb_single' ); ?>" id="<?php $this->field_id( 'breadcrumb_single' ); ?>" value="1"<?php checked( $this->get_field_value( 'breadcrumb_single' ) ); ?> />
			<?php _e( 'Posts', 'equity' ); ?></label>

			<label for="<?php $this->field_id( 'breadcrumb_page' ); ?>"><input type="checkbox" name="<?php $this->field_name( 'breadcrumb_page' ); ?>" id="<?php $this->field_id( 'breadcrumb_page' ); ?>" value="1"<?php checked( $this->get_field_value( 'breadcrumb_page' ) ); ?> />
			<?php _e( 'Pages', 'equity' ); ?></label>

			<label for="<?php $this->field_id( 'breadcrumb_archive' ); ?>"><input type="checkbox" name="<?php $this->field_name( 'breadcrumb_archive' ); ?>" id="<?php $this->field_id( 'breadcrumb_archive' ); ?>" value="1"<?php checked( $this->get_field_value( 'breadcrumb_archive' ) ); ?> />
			<?php _e( 'Archives', 'equity' ); ?></label>

			<label for="<?php $this->field_id( 'breadcrumb_404' ); ?>"><input type="checkbox" name="<?php $this->field_name( 'breadcrumb_404' ); ?>" id="<?php $this->field_id( 'breadcrumb_404' ); ?>" value="1"<?php checked( $this->get_field_value( 'breadcrumb_404' ) ); ?> />
			<?php _e( '404 Page', 'equity' ); ?></label>

			<label for="<?php $this->field_id( 'breadcrumb_attachment' ); ?>"><input type="checkbox" name="<?php $this->field_name( 'breadcrumb_attachment' ); ?>" id="<?php $this->field_id( 'breadcrumb_attachment' ); ?>" value="1"<?php checked( $this->get_field_value( 'breadcrumb_attachment' ) ); ?> />
			<?php _e( 'Attachment Page', 'equity' ); ?></label>
		</p>

		<p><span class="description"><?php _e( 'Breadcrumbs are a great way of letting your visitors find out where they are on your site with just a glance. You can enable/disable them on certain areas of your site.', 'equity' ); ?></span></p>
		<?php

	}

	/**
	 * Callback for Theme Settings Blog page template meta box.
	 *
	 * @since 1.0
	 *
	 * @uses \EQUITY_Admin::get_field_id()    Construct field ID.
	 * @uses \EQUITY_Admin::get_field_name()  Construct field name.
	 * @uses \EQUITY_Admin::get_field_value() Retrieve value of key under $this->settings_field.
	 *
	 * @see \EQUITY_Admin_Settings::metaboxes() Register meta boxes on the Theme Settings page.
	 */
	function blogpage_box() {

		?>
		<p><span class="description"><?php _e( 'These settings apply to any page given the "Blog" page template, not the homepage or post archive pages.', 'equity' ); ?></span></p>

		<hr class="div" />

		<p>
			<label for="<?php $this->field_id( 'blog_cat' ); ?>"><?php _e( 'Display which category:', 'equity' ); ?></label>
			<?php wp_dropdown_categories( array( 'selected' => $this->get_field_value( 'blog_cat' ), 'name' => $this->get_field_name( 'blog_cat' ), 'orderby' => 'Name', 'hierarchical' => 1, 'show_option_all' => __( 'All Categories', 'equity' ), 'hide_empty' => '0' ) ); ?>
		</p>

		<p>
			<label for="<?php $this->field_id( 'blog_cat_exclude' ); ?>"><?php _e( 'Exclude the following Category IDs:', 'equity' ); ?><br />
				<input type="text" name="<?php $this->field_name( 'blog_cat_exclude' ); ?>" class="regular-text" id="<?php $this->field_id( 'blog_cat_exclude' ); ?>" value="<?php echo esc_attr( $this->get_field_value( 'blog_cat_exclude' ) ); ?>" />
				<br /><small><strong><?php _e( 'Comma separated - 1,2,3 for example', 'equity' ); ?></strong></small>
			</label>
		</p>

		<p>
			<label for="<?php $this->field_id( 'blog_cat_num' ); ?>"><?php _e( 'Number of Posts to Show:', 'equity' ); ?></label>
			<input type="text" name="<?php $this->field_name( 'blog_cat_num' ); ?>" id="<?php $this->field_id( 'blog_cat_num' ); ?>" value="<?php echo esc_attr( $this->get_field_value( 'blog_cat_num' ) ); ?>" size="2" />
		</p>
		<?php

	}

	/**
	 * Callback for Theme Settings Header / Footer Scripts meta box.
	 *
	 * @since 1.0
	 *
	 * @uses \EQUITY_Admin::get_field_id()    Construct field ID.
	 * @uses \EQUITY_Admin::get_field_name()  Construct field name.
	 * @uses \EQUITY_Admin::get_field_value() Retrieve value of key under $this->settings_field.
	 *
	 * @see \EQUITY_Admin_Settings::metaboxes() Register meta boxes on the Theme Settings page.
	 */
	function scripts_box() {

		?>
		<p>
			<label for="<?php $this->field_id( 'header_scripts' ); ?>"><?php printf( __( 'Enter scripts or code you would like output to %s:', 'equity' ), equity_code( 'wp_head()' ) ); ?></label>
		</p>

		<textarea name="<?php $this->field_name( 'header_scripts' ); ?>" class="large-text" id="<?php $this->field_id( 'header_scripts' ); ?>" cols="78" rows="8"><?php echo esc_textarea( $this->get_field_value( 'header_scripts' ) ); ?></textarea>

		<p><span class="description"><?php printf( __( 'The %1$s hook executes immediately before the closing %2$s tag in the document source.', 'equity' ), equity_code( 'wp_head()' ), equity_code( '</head>' ) ); ?></span></p>

		<hr class="div" />

		<p>
			<label for="<?php $this->field_id( 'footer_scripts' ); ?>"><?php printf( __( 'Enter scripts or code you would like output to %s:', 'equity' ), equity_code( 'wp_footer()' ) ); ?></label>
		</p>

		<textarea name="<?php $this->field_name( 'footer_scripts' ); ?>" class="large-text" id="<?php $this->field_id( 'footer_scripts' ); ?>" cols="78" rows="8"><?php echo esc_textarea( $this->get_field_value( 'footer_scripts' ) ); ?></textarea>

		<p><span class="description"><?php printf( __( 'The %1$s hook executes immediately before the closing %2$s tag in the document source.', 'equity' ), equity_code( 'wp_footer()' ), equity_code( '</body>' ) ); ?></span></p>
		<?php

	}

}
