<?php
/**
 * Equity Framework
 *
 * WARNING: This file is part of the core Equity Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Equity\Admin
 * @author  IDX, LLC
 * @license GPL-2.0+
 * @link    
 */

add_action( 'show_user_profile', 'equity_user_archive_fields' );
add_action( 'edit_user_profile', 'equity_user_archive_fields' );
/**
 * Add fields for author archives contents to the user edit screen.
 *
 * Checkbox fields are:
 *
 * * Enable Author Box on this User's Posts?
 * * Enable Author Box on this User's Archives?
 *
 * @since 1.3
 *
 * @param \WP_User $user User object.
 *
 * @return false Return false if current user can not edit users.
 */
function equity_user_archive_fields( $user ) {

	if ( ! current_user_can( 'edit_users', $user->ID ) )
		return false;

	?>
	<h3><?php _e( 'Author Box Settings', 'equity' ); ?></h3>
	<p><span class="description"><?php _e( 'These settings apply to this author\'s single and archive pages.', 'equity' ); ?></span></p>
	<table class="form-table">
		<tbody>
			<tr>
				<th scope="row" valign="top"><?php _e( 'Author Box', 'equity' ); ?></th>
				<td>
					<label for="meta[equity_author_box_single]"><input id="meta[equity_author_box_single]" name="meta[equity_author_box_single]" type="checkbox" value="1" <?php checked( get_the_author_meta( 'equity_author_box_single', $user->ID ) ); ?> />
					<?php _e( 'Enable Author Box on this User\'s Posts?', 'equity' ); ?></label><br />

					<label for="meta[equity_author_box_archive]"><input id="meta[equity_author_box_archive]" name="meta[equity_author_box_archive]" type="checkbox" value="1" <?php checked( get_the_author_meta( 'equity_author_box_archive', $user->ID ) ); ?> />
					<?php _e( 'Enable Author Box on this User\'s Archives?', 'equity' ); ?></label>
				</td>
			</tr>
		</tbody>
	</table>
	<?php

}

add_action( 'personal_options_update',  'equity_user_meta_save' );
add_action( 'edit_user_profile_update', 'equity_user_meta_save' );
/**
 * Update user meta when user edit page is saved.
 *
 * @since 1.3
 *
 * @param integer $user_id User ID
 *
 * @return null Returns null if current user can not edit users.
 */
function equity_user_meta_save( $user_id ) {

	if ( ! current_user_can( 'edit_users', $user_id ) )
		return;

	// if ( ! isset( $_POST['meta'] ) )
	// 	return;

	$defaults = array(
		'equity_author_box_single'  => '',
		'equity_author_box_archive' => '',
	);

	/**
	 * Filter the user meta defaults array.
	 *
	 * Allows developer to filter the default array of user meta key => value pairs.
	 *
	 * @since 1.3
	 * 
	 * @param array $defaults Default user meta array.
	 */
	$defaults = apply_filters( 'equity_user_meta_defaults', $defaults );

	$meta = wp_parse_args( $_POST['meta'], $defaults );

	foreach ( $meta as $key => $value )
		update_user_meta( $user_id, $key, $value );

}