<?php
/**
 * Equity Framework
 *
 * WARNING: This file is part of the core Equity Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 * 
 * Custom template tags for this theme.
 *
 * @package Equity\Assets
 * @author  IDX, LLC
 * @license GPL-2.0+
 * @link    
 */

add_action( 'equity_meta', 'equity_load_stylesheets' );
/**
 * Echo reference to the foundation style sheet, the main style sheet, and font awesome style sheet, and custom css if theme support exists
 *
 * If a child theme is active, it loads the child theme's stylesheet, otherwise, it loads the Equity style sheet.
 *
 * @since 1.0
 *
 * @see equity_enqueue_foundation_stylesheet() Enqueue foundation style sheet.
 * @see equity_enqueue_main_stylesheet() Enqueue main style sheet.
 * @see equity_enqueue_print_stylesheet() Enqueue print style sheet.
 */
function equity_load_stylesheets() {

	add_action( 'wp_enqueue_scripts', 'equity_enqueue_foundation_stylesheet', 5 );
	add_action( 'wp_enqueue_scripts', 'equity_enqueue_main_stylesheet', 5 );
	add_action( 'wp_enqueue_scripts', 'equity_enqueue_fontawesome_stylesheet', 10 );
	add_action( 'wp_enqueue_scripts', 'equity_enqueue_properticons_stylesheet', 5 );
	add_action( 'wp_enqueue_scripts', 'equity_enqueue_print_stylesheet', 5 );
	add_action( 'wp_enqueue_scripts', 'equity_enqueue_google_fonts_stylesheet', 5 );

	//* Register Welcome page CSS, enqueued if called for
	wp_register_style( 'equity-welcome-css', EQUITY_CSS_URL . '/style-welcome.css', array(), null );

	//* Register OWL Carousel CSS for use in listings widget
	wp_register_style( 'owl-css', EQUITY_CSS_URL . '/owl.carousel.css', array(), null );
	wp_register_style( 'owl2-css', EQUITY_CSS_URL . '/owl2.carousel.css', array(), null );

}

/**
 * Enqueue foundation style sheet.
 *
 * Properly enqueue the foundation style sheet.
 *
 * @since 1.0
 * 
 * @uses PARENT_URL
 * @uses PARENT_THEME_VERSION
 */
function equity_enqueue_foundation_stylesheet() {

	wp_enqueue_style( 'equity-foundation', PARENT_URL . '/lib/css/foundation.css', false, null );
}

/**
 * Enqueue main style sheet.
 *
 * Properly enqueue the main style sheet.
 *
 * @since 1.0
 *
 * @uses CHILD_THEME_NAME
 * @uses CHILD_THEME_VERSION
 * @uses PARENT_THEME_VERSION
 */
function equity_enqueue_main_stylesheet() {

	$version = defined( 'CHILD_THEME_VERSION' ) && CHILD_THEME_VERSION ? CHILD_THEME_VERSION : PARENT_THEME_VERSION;
	$handle  = defined( 'CHILD_THEME_NAME' ) && CHILD_THEME_NAME ? sanitize_title_with_dashes( CHILD_THEME_NAME ) : 'child-theme';

	if ( file_exists( get_stylesheet_directory() . "/style.min.css" ) ) {
		wp_enqueue_style( $handle, get_stylesheet_directory_uri() . "/style.min.css", array(), $version );
	} else {
		wp_enqueue_style( $handle, get_stylesheet_uri(), array(), $version );
	}

}

/**
 * Enqueue IDX Widgets style sheet
 * 
 * @since 1.1
 *
 * @uses PARENT_THEME_VERSION, CHILD_THEME_VERSION, EQUITY_CSS_URL
 */
function equity_enqueue_idx_stylesheet() {

	if(file_exists( get_stylesheet_directory() . "/idx-widgets.css" )) {
		wp_enqueue_style( 'equity-idx', get_stylesheet_directory_uri() . "/idx-widgets.css", array(), null );
	} else {
		wp_enqueue_style( 'equity-idx', EQUITY_CSS_URL . "/idx-widgets.css", array(), null );
	}

}

/**
 * Enqueue font awesome style sheet from CDN (prevents cross-domain font loading issue).
 *
 * Properly enqueue the font awesome style sheet.
 *
 * @see http://fortawesome.github.io/Font-Awesome/get-started/
 * 
 * @since 1.0
 */
function equity_enqueue_fontawesome_stylesheet() {
	wp_enqueue_style( 'font-awesome-5.8.2', 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css', array(), '5.8.2' );
}

/**
 * Enqueue Properticons style sheet from CDN (prevents cross-domain font loading issue).
 *
 * Properly enqueue the Properticons style sheet.
 *
 * @see http://agentevolution.github.io/properticons/
 * 
 * @since 1.0
 */
function equity_enqueue_properticons_stylesheet() {

	wp_enqueue_style( 'properticons', 'https://s3.amazonaws.com/properticons/css/properticons.css', false, null );

}

/**
 * Enqueue Print friendly style sheet
 * 
 * @since 1.0
 */
function equity_enqueue_print_stylesheet() {

	if(file_exists( get_stylesheet_directory() . "/style-print.css" )) {
		wp_enqueue_style( 'equity-print', get_stylesheet_directory_uri() . "/style-print.css", array(), null, 'print' );
	} else {
		wp_enqueue_style( 'equity-print', EQUITY_CSS_URL . "/style-print.css", array(), null, 'print' );
	}

}

/**
 * Add link to Google Fonts stylesheet
 *
 * Applies equity_google_fonts() filter
 * 
 * @since 1.0
 */
function equity_enqueue_google_fonts_stylesheet() {

	//* Default fonts if no filter added in child theme
	$equity_google_fonts = 'Roboto:100,300,500,300italic,500italic';

	$equity_google_fonts = apply_filters( 'equity_google_fonts', $equity_google_fonts );

	wp_enqueue_style( 'equity-google-fonts', '//fonts.googleapis.com/css?family=' . $equity_google_fonts . '', array(), null  );

}

add_action( 'wp_head', 'equity_display_custom_css', 199 );
/**
 * Output custom CSS to wp_head
 *
 * @since 1.0
 */
function equity_display_custom_css() {
	$custom_css_support = get_theme_support( 'equity-custom-css' );
	if ( ! $custom_css_support )
		return; // if no theme support, bail
	
	$custom_css = get_option( 'custom_css' );
	echo '<style type="text/css" id="equity-custom-panel">/* Custom CSS */';
	echo $custom_css;
	echo '</style>';
}

add_action( 'admin_print_styles', 'equity_load_admin_styles' );
/**
 * Enqueue Equity admin styles.
 *
 * @since 1.0
 *
 * @uses EQUITY_CSS_URL
 */
function equity_load_admin_styles() {

	wp_enqueue_style( 'equity_admin_css', EQUITY_CSS_URL . "/admin.css", array(), null );

}

add_action( 'init', 'equity_add_editor_styles' );
/**
 * Add Equity editor styles. Only adds if file exists. Will check child theme first.
 *
 * @since 1.0
 *
 * @see http://codex.wordpress.org/Function_Reference/add_editor_style
 */
function equity_add_editor_styles() {

	if ( file_exists( get_stylesheet_directory() . "/style-editor.css" ) ) {
		add_editor_style( 'style-editor.css' );
		add_editor_style( 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css');
	} else {
		add_editor_style( EQUITY_CSS_URL . "/style-editor.css" );
		add_editor_style( 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css');
	}
}
