<?php
/**
 * Equity Framework
 *
 * WARNING: This file is part of the core Equity Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Equity\Breadcrumbs
 * @author  IDX, LLC
 * @license GPL-2.0+
 * @link    
 */

/**
 * Helper function for the Equity Breadcrumb Class.
 *
 * @since 1.0
 *
 * @global EQUITY_Breadcrumb $_equity_breadcrumb
 *
 * @param array $args Breadcrumb arguments
 */
function equity_breadcrumb( $args = array() ) {

	global $_equity_breadcrumb;

	if ( ! $_equity_breadcrumb )
		$_equity_breadcrumb = new EQUITY_Breadcrumb;

	$_equity_breadcrumb->output( $args );

}

add_action( 'equity_before_loop', 'equity_do_breadcrumbs' );
/**
 * Display Breadcrumbs above the Loop. Concedes priority to popular breadcrumb
 * plugins.
 *
 * @since 1.0
 *
 * @return null Return null if a popular breadcrumb plugin is active
 */
function equity_do_breadcrumbs() {

	if (
		( ( 'posts' === get_option( 'show_on_front' ) && is_home() ) && ! equity_get_option( 'breadcrumb_home' ) ) ||
		( ( 'page' === get_option( 'show_on_front' ) && is_front_page() ) && ! equity_get_option( 'breadcrumb_front_page' ) ) ||
		( ( 'page' === get_option( 'show_on_front' ) && is_home() ) && ! equity_get_option( 'breadcrumb_posts_page' ) ) ||
		( is_single() && ! equity_get_option( 'breadcrumb_single' ) ) ||
		( is_page() && ! equity_get_option( 'breadcrumb_page' ) ) ||
		( ( is_archive() || is_search() ) && ! equity_get_option( 'breadcrumb_archive' ) ) ||
		( is_404() && ! equity_get_option( 'breadcrumb_404' ) ) ||
		( is_attachment() && ! equity_get_option( 'breadcrumb_attachment' ) )
	)
		return;

	if ( function_exists( 'bcn_display' ) ) {
		echo '<div class="breadcrumb" itemprop="breadcrumb">';
		bcn_display();
		echo '</div>';
	}
	elseif ( function_exists( 'breadcrumbs' ) ) {
		breadcrumbs();
	}
	elseif ( function_exists( 'crumbs' ) ) {
		crumbs();
	}
	elseif ( class_exists( 'WPSEO_Breadcrumbs' ) && equity_get_option( 'breadcrumbs-enable', 'wpseo_internallinks' ) ) {
		yoast_breadcrumb( '<div class="breadcrumb" itemprop="breadcrumb">', '</div>' );
	}
	elseif( function_exists( 'yoast_breadcrumb' ) && ! class_exists( 'WPSEO_Breadcrumbs' ) ) {
		yoast_breadcrumb( '<div class="breadcrumb" itemprop="breadcrumb">', '</div>' );
	}
	else {
		equity_breadcrumb();
	}

}
