<?php
/**
 * Equity Framework
 *
 * WARNING: This file is part of the core Equity Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Equity\Menus
 * @author  IDX, LLC
 * @license GPL-2.0+
 * @link    
 */

/**
 * Determine if a child theme supports a particular Equity nav menu.
 *
 * @since 1.0
 *
 * @param string $menu Name of the menu to check support for.
 *
 * @return boolean True if menu supported, false otherwise.
 */
function equity_nav_menu_supported( $menu ) {

	if ( ! current_theme_supports( 'equity-menus' ) )
		return false;

	$menus = get_theme_support( 'equity-menus' );

	if ( array_key_exists( $menu, (array) $menus[0] ) )
		return true;

	return false;

}

/**
 * Return the markup to display a menu consistent with the Equity format.
 *
 * Applies the `equity_$location_nav` filter e.g. `equity_header_nav`.
 *
 * @since 1.0
 *
 * @uses equity_markup()             Contextual markup.
 * @uses equity_structural_wrap()    Adds optional internal wrap divs.
 *
 * @param string $args Menu arguments.
 *
 * @return string Navigation menu markup.
 */
function equity_get_nav_menu( $args = array() ) {

	$args = wp_parse_args( $args, array(
		'theme_location' => '',
		'container'      => '',
		'menu_class'     => 'menu equity-nav-menu',
		'link_before'    => equity_markup(
			array(
				'open'    => '<span %s>',
				'context' => 'nav-link-wrap',
				'echo'    => false,
			)
		),
		'link_after'     => equity_markup(
			array(
				'close'   => '</span>',
				'context' => 'nav-link-wrap',
				'echo'    => false,
			)
		),
		'echo'           => 0,
	) );

	// If a menu is not assigned to theme location, abort.
	if ( ! has_nav_menu( $args['theme_location'] ) ) {
		return null;
	}

	$sanitized_location = sanitize_key( $args['theme_location'] );

	$nav = wp_nav_menu( $args );

	//* Do nothing if there is nothing to show
	if ( ! $nav ) {
		return;
	}

	$nav_markup_open  = equity_structural_wrap( 'menu-' . $sanitized_location, 'open', 0 );
	$nav_markup_close = equity_structural_wrap( 'menu-' . $sanitized_location, 'close', 0 );

	$params = array(
		'theme_location' => $args['theme_location'],
	);
	
	if ( current_theme_supports( 'equity-accessibility' ) ) {
		$nav_output = equity_markup( array(
			'open'    => '<nav %s>',
			'close'   => '</nav>',
			'context' => 'nav-' . $sanitized_location,
			'content' => $nav_markup_open . $nav . $nav_markup_close,
			'echo'    => false,
			'params'  => $params,
		) );
	} else {
		$nav_output = $nav_markup_open . $nav . $nav_markup_close;
	}

	$filter_location = 'equity_' . $sanitized_location . '_nav';

	/**
	 * Filter the navigation markup.
	 *
	 * @since 1.0
	 *
	 * @param string $nav_output Opening container markup, nav, closing container markup.
	 * @param string $nav Navigation list (`<ul>`).
	 * @param array $args {
	 *     Arguments for `wp_nav_menu()`.
	 *
	 *     @type string $theme_location Menu location ID.
	 *     @type string $container Container markup.
	 *     @type string $menu_class Class(es) applied to the `<ul>`.
	 *     @type bool $echo 0 to indicate `wp_nav_menu()` should return not echo.
	 * }
	 */
	return apply_filters( $filter_location, $nav_output, $nav, $args );
}

/**
 * Echo the output from `equity_get_nav_menu()`.
 *
 * @since 1.0
 *
 * @uses equity_get_nav_menu() Return the markup to display a menu consistent with the Equity format.
 *
 * @param string $args Menu arguments.
 * @param bool display `equity_default_menu` callback 
 */
function equity_nav_menu( $args, $menu_default ) {
	echo equity_get_nav_menu( $args, $menu_default );
}

add_filter( 'wp_page_menu_args', 'equity_page_menu_args' );
/**
 * Get our wp_nav_menu() fallback, wp_page_menu(), to show a home link.
 *
 * @param array $args Configuration arguments.
 * @return array
 */
function equity_page_menu_args( $args ) {
	$args['show_home'] = true;
	return $args;
}

/**
 * Adds default menu fallback callback if no menu exists
 *
 * @since 1.0
 */
function equity_default_menu() {
	echo '<ul class="title-area"><li class="name"><a href="' . home_url() . '/wp-admin/nav-menus.php">' . __( 'Please Setup your Menus', 'equity' ) . '</a></li></ul>';
}

add_action( 'after_setup_theme', 'equity_set_user_menus');
/**
 * Unhides description and CSS classes from Menus page for improved usability with theme features.
 *
 * @since 1.0
 */
function equity_set_user_menus(){
	$userid = get_current_user_id();
	update_user_option( $userid, 'managenav-menuscolumnshidden', array('link-target', 'xfn'), true);
}

add_action( "load-nav-menus.php", 'equity_add_menu_help_tab', 999 );
/**
 * Adds contextual help to the menus page
 *
 * @since 1.0
 */
function equity_add_menu_help_tab () {
	$screen = get_current_screen();

	$menu_page_help = '<p>' . __( 'CSS Classes can be added to menu items to create Labels and Dividers.', 'equity' ) . '</p>';
	$menu_page_help .= '<p>' . __( 'To add a <em>Label</em>, add a CSS class of "<strong>label</strong>" (without quotes). The Title is used as the Label text. Use a pound sign (#) for the URL.', 'equity' ) . '</p>';
	$menu_page_help .= '<p>' . __( 'To add a <em>Divider</em>, add a CSS class of "<strong>divider</strong>" (without quotes). The Title will not be displayed. Use a pound sign (#) for the URL.', 'equity' ) . '</p>';

	// Add equity_menu_help_tab if current screen is Menus Page
	$screen->add_help_tab( array(
		'id'	    => 'equity_menu_help_tab',
		'title'	    => __('Menu Options'),
		'content'	=> $menu_page_help,
	) );
}